-- ============================================
-- Admin Neighborhoods table
-- Stores neighborhoods (quartiers) by city for the wizard
-- ============================================

CREATE TABLE IF NOT EXISTS admin_neighborhoods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city TEXT NOT NULL,
  name TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (city, name)
);

-- Index for fast lookups by city
CREATE INDEX IF NOT EXISTS idx_admin_neighborhoods_city ON admin_neighborhoods (city);

-- RLS
ALTER TABLE admin_neighborhoods ENABLE ROW LEVEL SECURITY;

-- Allow service role full access
CREATE POLICY admin_neighborhoods_service_all ON admin_neighborhoods
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Seed with popular neighborhoods (city names match MOROCCAN_CITIES exactly)
INSERT INTO admin_neighborhoods (city, name) VALUES
  -- Casablanca
  ('Casablanca', 'Aïn Diab'), ('Casablanca', 'Maârif'), ('Casablanca', 'Anfa'),
  ('Casablanca', 'Gauthier'), ('Casablanca', 'Bourgogne'), ('Casablanca', 'Racine'),
  ('Casablanca', 'Oasis'), ('Casablanca', 'Californie'), ('Casablanca', 'Aïn Sebaâ'),
  ('Casablanca', 'Hay Mohammadi'), ('Casablanca', 'Sidi Belyout'), ('Casablanca', 'Mers Sultan'),
  ('Casablanca', 'Derb Sultan'), ('Casablanca', 'Habous'), ('Casablanca', 'Ancienne Médina'),
  ('Casablanca', 'Bouskoura'), ('Casablanca', 'Aïn Chock'), ('Casablanca', 'Sidi Maârouf'),
  ('Casablanca', '2 Mars'), ('Casablanca', 'Palmier'),
  -- Marrakech
  ('Marrakech', 'Guéliz'), ('Marrakech', 'Médina'), ('Marrakech', 'Hivernage'),
  ('Marrakech', 'Palmeraie'), ('Marrakech', 'Agdal'), ('Marrakech', 'Targa'),
  ('Marrakech', 'Amelkis'), ('Marrakech', 'Route de l''Ourika'), ('Marrakech', 'Route de Fès'),
  ('Marrakech', 'Sidi Ghanem'), ('Marrakech', 'Mellah'), ('Marrakech', 'Kasbah'),
  ('Marrakech', 'Bab Doukkala'), ('Marrakech', 'Daoudiate'), ('Marrakech', 'Massira'),
  -- Rabat
  ('Rabat', 'Océan'), ('Rabat', 'Agdal'), ('Rabat', 'Médina'),
  ('Rabat', 'Hay Riad'), ('Rabat', 'Souissi'), ('Rabat', 'Les Orangers'),
  ('Rabat', 'Aviation'), ('Rabat', 'Hassan'), ('Rabat', 'Youssoufia'),
  ('Rabat', 'Akkari'), ('Rabat', 'Diour Jamaâ'), ('Rabat', 'Takaddoum'),
  ('Rabat', 'Yacoub El Mansour'),
  -- Fès
  ('Fès', 'Ville Nouvelle'), ('Fès', 'Fès el-Bali'), ('Fès', 'Fès Jdid'),
  ('Fès', 'Atlas'), ('Fès', 'Saïss'), ('Fès', 'Narjiss'),
  ('Fès', 'Mont Fleuri'), ('Fès', 'Aïn Kadous'), ('Fès', 'Oued Fès'),
  ('Fès', 'Bensouda'), ('Fès', 'Route d''Immouzer'),
  -- Tanger
  ('Tanger', 'Médina'), ('Tanger', 'Ville Nouvelle'), ('Tanger', 'Malabata'),
  ('Tanger', 'Marshan'), ('Tanger', 'Iberia'), ('Tanger', 'California'),
  ('Tanger', 'Boukhalef'), ('Tanger', 'Tanja Balia'), ('Tanger', 'Mesnana'),
  ('Tanger', 'Gzenaya'), ('Tanger', 'Cap Spartel'), ('Tanger', 'Vieille Montagne'),
  -- Agadir
  ('Agadir', 'Centre Ville'), ('Agadir', 'Nouveau Talborjt'), ('Agadir', 'Talborjt'),
  ('Agadir', 'Charaf'), ('Agadir', 'Hay Mohammadi'), ('Agadir', 'Founty'),
  ('Agadir', 'Sonaba'), ('Agadir', 'Cité Suisse'), ('Agadir', 'Secteur Touristique'),
  ('Agadir', 'Marina'), ('Agadir', 'Anza'), ('Agadir', 'Tikiouine'),
  -- Meknès
  ('Meknès', 'Ville Nouvelle'), ('Meknès', 'Médina'), ('Meknès', 'Hamria'),
  ('Meknès', 'Marjane'), ('Meknès', 'Zitoune'), ('Meknès', 'Sidi Bouzekri'),
  ('Meknès', 'Toulal'), ('Meknès', 'Bassatine'), ('Meknès', 'Aïn Slougui'),
  ('Meknès', 'Belle Vue'),
  -- Mohammedia
  ('Mohammedia', 'Centre Ville'), ('Mohammedia', 'Plage'), ('Mohammedia', 'Kasbah'),
  -- El Jadida
  ('El Jadida', 'Centre Ville'), ('El Jadida', 'Cité Portugaise'), ('El Jadida', 'Plage'),
  -- Essaouira
  ('Essaouira', 'Médina'), ('Essaouira', 'Diabat'), ('Essaouira', 'Plage'),
  -- Tétouan
  ('Tétouan', 'Médina'), ('Tétouan', 'Ville Nouvelle'), ('Tétouan', 'Martil'),
  -- Oujda
  ('Oujda', 'Centre Ville'), ('Oujda', 'Médina'), ('Oujda', 'Lazaret'),
  -- Kénitra
  ('Kénitra', 'Centre Ville'), ('Kénitra', 'Mehdia'), ('Kénitra', 'Bir Rami'),
  -- Salé
  ('Salé', 'Centre Ville'), ('Salé', 'Médina'), ('Salé', 'Tabriquet')
ON CONFLICT (city, name) DO NOTHING;
