// Liste complète des pays du monde avec indicatifs et villes principales
export type CountryData = {
  code: string;
  name: string;
  flag: string;
  dialCode: string;
  cities: string[];
};

export const COUNTRIES_DATA: CountryData[] = [
  // Afrique
  {
    code: "DZ",
    name: "Algérie",
    flag: "🇩🇿",
    dialCode: "+213",
    cities: ["Alger", "Oran", "Constantine", "Annaba", "Blida", "Batna", "Sétif", "Djelfa", "Sidi Bel Abbès", "Biskra", "Tébessa", "El Oued", "Skikda", "Tiaret", "Béjaïa", "Tlemcen", "Ouargla", "Béchar", "Mostaganem", "Bordj Bou Arreridj"],
  },
  {
    code: "AO",
    name: "Angola",
    flag: "🇦🇴",
    dialCode: "+244",
    cities: ["Luanda", "Huambo", "Lobito", "Benguela", "Lucapa", "Kuito", "Malanje", "Namibe", "Soyo", "Cabinda"],
  },
  {
    code: "BJ",
    name: "Bénin",
    flag: "🇧🇯",
    dialCode: "+229",
    cities: ["Cotonou", "Porto-Novo", "Parakou", "Djougou", "Bohicon", "Kandi", "Abomey", "Natitingou", "Lokossa", "Ouidah"],
  },
  {
    code: "BW",
    name: "Botswana",
    flag: "🇧🇼",
    dialCode: "+267",
    cities: ["Gaborone", "Francistown", "Molepolole", "Serowe", "Selibe Phikwe", "Maun", "Kanye", "Mahalapye", "Mogoditshane", "Mochudi"],
  },
  {
    code: "BF",
    name: "Burkina Faso",
    flag: "🇧🇫",
    dialCode: "+226",
    cities: ["Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Banfora", "Ouahigouya", "Pouytenga", "Kaya", "Tenkodogo", "Fada N'gourma", "Dédougou"],
  },
  {
    code: "BI",
    name: "Burundi",
    flag: "🇧🇮",
    dialCode: "+257",
    cities: ["Bujumbura", "Gitega", "Muyinga", "Ngozi", "Ruyigi", "Kayanza", "Bururi", "Makamba", "Cibitoke", "Bubanza"],
  },
  {
    code: "CM",
    name: "Cameroun",
    flag: "🇨🇲",
    dialCode: "+237",
    cities: ["Douala", "Yaoundé", "Garoua", "Bamenda", "Maroua", "Bafoussam", "Ngaoundéré", "Bertoua", "Kumba", "Loum", "Nkongsamba", "Edéa", "Kribi", "Limbé", "Ebolowa"],
  },
  {
    code: "CV",
    name: "Cap-Vert",
    flag: "🇨🇻",
    dialCode: "+238",
    cities: ["Praia", "Mindelo", "Santa Maria", "Assomada", "Pedra Badejo", "São Filipe", "Tarrafal", "Porto Novo", "Espargos"],
  },
  {
    code: "CF",
    name: "République centrafricaine",
    flag: "🇨🇫",
    dialCode: "+236",
    cities: ["Bangui", "Bimbo", "Berbérati", "Carnot", "Bambari", "Bouar", "Bossangoa", "Bria", "Bangassou", "Nola"],
  },
  {
    code: "TD",
    name: "Tchad",
    flag: "🇹🇩",
    dialCode: "+235",
    cities: ["N'Djamena", "Moundou", "Sarh", "Abéché", "Kélo", "Koumra", "Pala", "Am Timan", "Bongor", "Mongo"],
  },
  {
    code: "KM",
    name: "Comores",
    flag: "🇰🇲",
    dialCode: "+269",
    cities: ["Moroni", "Mutsamudu", "Fomboni", "Domoni", "Tsimbeo", "Adda-Douéni", "Sima", "Ouani", "Mirontsi", "Mbéni"],
  },
  {
    code: "CG",
    name: "Congo",
    flag: "🇨🇬",
    dialCode: "+242",
    cities: ["Brazzaville", "Pointe-Noire", "Dolisie", "Nkayi", "Owando", "Ouesso", "Madingou", "Sibiti", "Impfondo", "Mossendjo"],
  },
  {
    code: "CD",
    name: "RD Congo",
    flag: "🇨🇩",
    dialCode: "+243",
    cities: ["Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Kananga", "Kisangani", "Bukavu", "Goma", "Likasi", "Kolwezi", "Tshikapa", "Matadi", "Kikwit", "Mbandaka", "Uvira", "Butembo"],
  },
  {
    code: "CI",
    name: "Côte d'Ivoire",
    flag: "🇨🇮",
    dialCode: "+225",
    cities: ["Abidjan", "Bouaké", "Daloa", "Yamoussoukro", "San-Pédro", "Korhogo", "Man", "Divo", "Gagnoa", "Abengourou", "Anyama", "Agboville", "Grand-Bassam", "Dabou", "Séguéla"],
  },
  {
    code: "DJ",
    name: "Djibouti",
    flag: "🇩🇯",
    dialCode: "+253",
    cities: ["Djibouti", "Ali Sabieh", "Tadjoura", "Obock", "Dikhil", "Arta"],
  },
  {
    code: "EG",
    name: "Égypte",
    flag: "🇪🇬",
    dialCode: "+20",
    cities: ["Le Caire", "Alexandrie", "Gizeh", "Charm el-Cheikh", "Louxor", "Assouan", "Hurghada", "Port-Saïd", "Suez", "Ismaïlia", "Mansourah", "Tanta", "Zagazig", "Damiette", "Fayoum"],
  },
  {
    code: "GQ",
    name: "Guinée équatoriale",
    flag: "🇬🇶",
    dialCode: "+240",
    cities: ["Malabo", "Bata", "Ebebiyín", "Aconibe", "Añisoc", "Luba", "Evinayong", "Mongomo", "Riaba"],
  },
  {
    code: "ER",
    name: "Érythrée",
    flag: "🇪🇷",
    dialCode: "+291",
    cities: ["Asmara", "Keren", "Massawa", "Assab", "Mendefera", "Barentu", "Adi Keyh", "Adi Quala", "Dekemhare", "Senafe"],
  },
  {
    code: "SZ",
    name: "Eswatini",
    flag: "🇸🇿",
    dialCode: "+268",
    cities: ["Mbabane", "Manzini", "Big Bend", "Malkerns", "Nhlangano", "Piggs Peak", "Siteki", "Hluti"],
  },
  {
    code: "ET",
    name: "Éthiopie",
    flag: "🇪🇹",
    dialCode: "+251",
    cities: ["Addis-Abeba", "Dire Dawa", "Mek'ele", "Gondar", "Bahir Dar", "Hawassa", "Adama", "Jimma", "Dessie", "Harar", "Jijiga", "Shashamane", "Arba Minch", "Hosaena", "Debre Markos"],
  },
  {
    code: "GA",
    name: "Gabon",
    flag: "🇬🇦",
    dialCode: "+241",
    cities: ["Libreville", "Port-Gentil", "Franceville", "Oyem", "Moanda", "Mouila", "Lambaréné", "Tchibanga", "Koulamoutou", "Makokou"],
  },
  {
    code: "GM",
    name: "Gambie",
    flag: "🇬🇲",
    dialCode: "+220",
    cities: ["Banjul", "Serekunda", "Brikama", "Bakau", "Farafenni", "Lamin", "Nema Kunku", "Sukuta", "Brusubi", "Gunjur"],
  },
  {
    code: "GH",
    name: "Ghana",
    flag: "🇬🇭",
    dialCode: "+233",
    cities: ["Accra", "Kumasi", "Tamale", "Takoradi", "Ashaiman", "Tema", "Cape Coast", "Sekondi", "Obuasi", "Teshie", "Madina", "Koforidua", "Sunyani", "Ho", "Wa"],
  },
  {
    code: "GN",
    name: "Guinée",
    flag: "🇬🇳",
    dialCode: "+224",
    cities: ["Conakry", "Nzérékoré", "Kankan", "Kindia", "Labé", "Guéckédou", "Kissidougou", "Mamou", "Siguiri", "Boké", "Kamsar", "Faranah", "Dalaba", "Pita", "Macenta"],
  },
  {
    code: "GW",
    name: "Guinée-Bissau",
    flag: "🇬🇼",
    dialCode: "+245",
    cities: ["Bissau", "Bafatá", "Gabú", "Bissorã", "Bolama", "Cacheu", "Bubaque", "Catió", "Mansôa", "Farim"],
  },
  {
    code: "KE",
    name: "Kenya",
    flag: "🇰🇪",
    dialCode: "+254",
    cities: ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret", "Ruiru", "Kikuyu", "Thika", "Malindi", "Naivasha", "Kitale", "Machakos", "Lamu", "Garissa", "Nyeri"],
  },
  {
    code: "LS",
    name: "Lesotho",
    flag: "🇱🇸",
    dialCode: "+266",
    cities: ["Maseru", "Teyateyaneng", "Mafeteng", "Hlotse", "Mohale's Hoek", "Quthing", "Qacha's Nek", "Butha-Buthe", "Mokhotlong"],
  },
  {
    code: "LR",
    name: "Liberia",
    flag: "🇱🇷",
    dialCode: "+231",
    cities: ["Monrovia", "Gbarnga", "Kakata", "Bensonville", "Harper", "Voinjama", "Buchanan", "Zwedru", "Harbel", "Pleebo"],
  },
  {
    code: "LY",
    name: "Libye",
    flag: "🇱🇾",
    dialCode: "+218",
    cities: ["Tripoli", "Benghazi", "Misrata", "Tarhuna", "Al Khums", "Zawiya", "Ajdabiya", "Syrte", "Zliten", "Tobrouk", "Sabha", "Derna", "Al Bayda", "Gharyan", "Sabratha"],
  },
  {
    code: "MG",
    name: "Madagascar",
    flag: "🇲🇬",
    dialCode: "+261",
    cities: ["Antananarivo", "Toamasina", "Antsirabe", "Fianarantsoa", "Mahajanga", "Toliara", "Antsiranana", "Ambovombe", "Morondava", "Nosy Be", "Antalaha", "Manakara", "Ambatondrazaka", "Farafangana", "Fort-Dauphin"],
  },
  {
    code: "MW",
    name: "Malawi",
    flag: "🇲🇼",
    dialCode: "+265",
    cities: ["Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Kasungu", "Mangochi", "Karonga", "Salima", "Nkhotakota", "Liwonde"],
  },
  {
    code: "ML",
    name: "Mali",
    flag: "🇲🇱",
    dialCode: "+223",
    cities: ["Bamako", "Sikasso", "Mopti", "Koutiala", "Kayes", "Ségou", "Gao", "Tombouctou", "Kati", "San", "Kolokani", "Niono", "Bougouni", "Nioro du Sahel", "Bandiagara"],
  },
  {
    code: "MR",
    name: "Mauritanie",
    flag: "🇲🇷",
    dialCode: "+222",
    cities: ["Nouakchott", "Nouadhibou", "Kiffa", "Kaédi", "Rosso", "Zouérat", "Atar", "Néma", "Sélibabi", "Aïoun el Atrouss", "Tidjikja", "Akjoujt", "Aioun el Atrouss"],
  },
  {
    code: "MU",
    name: "Maurice",
    flag: "🇲🇺",
    dialCode: "+230",
    cities: ["Port-Louis", "Beau Bassin-Rose Hill", "Vacoas-Phoenix", "Curepipe", "Quatre Bornes", "Triolet", "Goodlands", "Centre de Flacq", "Bel Air Rivière Sèche", "Mahébourg"],
  },
  {
    code: "MA",
    name: "Maroc",
    flag: "🇲🇦",
    dialCode: "+212",
    cities: ["Aday", "Afourer", "Agadir", "Agdz", "Aghbala", "Aglou", "Agouraï", "Aguelmam Azegza", "Aguelmous", "Ahermoumou", "Ahfir", "Ain Aicha", "Ain Sfa", "Aïn Beni Mathar", "Aïn Cheggag", "Aïn Chkef", "Aïn Dorij", "Aïn El Aouda", "Aïn Harrouda", "Aïn Jemaa", "Aïn Karma", "Aïn Leuh", "Aïn Mediouna", "Aïn Sbit", "Aïn Taoujdate", "Aït Amira", "Aït Attab", "Aït Baha", "Aït Ben Haddou", "Aït Boubidmane", "Aït Faska", "Aït Hani", "Aït Iaâza", "Aït Ishaq", "Aït M'hamed", "Aït Majden", "Aït Melloul", "Aït Ouallal", "Aït Oumghar", "Aït Ourir", "Aït Sedrate", "Aït Seghrouchen", "Aït Tamlil", "Aït Youssef", "Ajdir", "Akka", "Aklim", "Aknoul", "Al Aroui", "Al Hoceima", "Alnif", "Amezmiz", "Amizmiz", "Amouguer", "Anezi", "Anjra", "Aoufous", "Aoulouz", "Aourir", "Aousserd", "Arazane", "Arbaoua", "Arfoud", "Asilah", "Asni", "Assa", "Assa-Zag", "Assahrij", "Azemmour", "Azilal", "Azla", "Azrou", "Bab Berred", "Bab Berret", "Bab Taza", "Bejaad", "Ben Ahmed", "Ben Guerir", "Ben Taïeb", "Beni Bouayach", "Beni Chiker", "Beni Ensar", "Béni Mellal", "Benslimane", "Berkane", "Berrechid", "Bhalil", "Bin El Ouidane", "Biougra", "Bir Anzarane", "Bir Gandouz", "Bir Jdid", "Bni Ansar", "Bni Ounjel Tafraout", "Bouabout", "Bouarfa", "Bouderbala", "Boufekrane", "Bouguedra", "Bouhdila", "Bouizakarne", "Boujad", "Boujaad", "Boujaâd", "Boujdour", "Bouknadel", "Boulaouane", "Boulemane", "Boumalne Dadès", "Bouskoura", "Bouznika", "Bradia", "Bzou", "Cabo Negro", "Casablanca", "Chefchaouen", "Chemaia", "Chichaoua", "Chtouka", "Dakhla", "Dar Bni Karrich", "Dar Chaâfai", "Dar Gueddari", "Dar Ould Zidouh", "Dcheira El Jihadia", "Dchira", "Debdou", "Demnate", "Douar Ain Chock", "Drarga", "Driouch", "El Aïoun", "El Aïoun Sidi Mellouk", "El Borouj", "El Borj", "El Brouj", "El Gara", "El Guerdane", "El Hajeb", "El Hanchane", "El Jadida", "El Kebab", "El Kelâa des Sraghna", "El Ksiba", "El Mansouria", "El Marsa", "El Menzel", "El Ouatia", "Enjil", "Erfoud", "Errachidia", "Es-Semara", "Essaouira", "Ezzahra", "Fam El Hisn", "Fès", "Figuig", "Fnideq", "Foum El Oued", "Fquih Ben Salah", "Ghafsai", "Ghmate", "Gleibat El Foula", "Goulmima", "Gourrama", "Guelmim", "Guelta Zemmour", "Guercif", "Gueznaia", "Guigou", "Had Bouhssoussen", "Had Court", "Had Kourt", "Had Soualem", "Hagounia", "Harhoura", "Hassi Berkane", "Hassi Labied", "Ifrane", "Ifrane Anti-Atlas", "Igherm", "Ighoud", "Iheddadene", "Imilchil", "Imintanoute", "Imlil", "Imouzzer du Kandar", "Imouzzer Ida Ou Tanane", "Imouzzer Kandar", "Imouzzer Marmoucha", "Imzouren", "Inezgane", "Issaguen", "Itzer", "Jbel Moussa", "Jebha", "Jemaa Shaim", "Jerada", "Jorf", "Jorf El Melha", "Jorf Lasfar", "Kalâa des Sraghna", "Kalaat Mgouna", "Karia Ba Mohamed", "Kariet Arkmane", "Kariat Arkmane", "Kasba Tadla", "Kasbat Tadla", "Kassita", "Kattara", "Kelâat M'Gouna", "Kénitra", "Kerrando", "Kerrouchen", "Ketama", "Khémisset", "Khemis Zemamra", "Khénifra", "Khenichet", "Khmis Sahel", "Khouribga", "Ksabi", "Ksar El Kébir", "Ksar el-Kébir", "Laâyoune", "Laattaouia", "Lagouira", "Lakhsas", "Lalla Mimouna", "Lalla Takerkoust", "Lamsid", "Laouamra", "Larache", "Layoune", "Loudaya", "Loulad", "Lqliâa", "M'diq", "M'hamid El Ghizlane", "M'rirt", "M'semrir", "Maaziz", "Madagh", "Marrakech", "Martil", "Massa", "Mechra Bel Ksiri", "Mechraa Bel Ksiri", "Mediouna", "Médiouna", "Mehdia", "Meknès", "Menara", "Merzouga", "Meski", "Midar", "Midelt", "Mijik", "Mirleft", "Missour", "Mogador", "Mohammédia", "Mokrisset", "Moulay Abdellah", "Moulay Bouselham", "Moulay Bousselham", "Moulay Brahim", "Moulay Idriss Zerhoun", "Moulay Yacoub", "Nador", "Nkob", "Nouaceur", "Oualidia", "Ouaouizaght", "Ouarzazate", "Ouazzane", "Oued Amlil", "Oued Laou", "Oued Zem", "Ouedzem", "Ouezzane", "Ouislane", "Oujda", "Oulad Ayad", "Ouled Ayad", "Ouled Berhil", "Ouled Frej", "Ouled Tayeb", "Ouled Teïma", "Ouled Teima", "Oulmès", "Oulmes", "Oum Dreyga", "Oum El Bouaghi", "Ourika", "Outat El Haj", "Ouzoud", "Rabat", "Ras El Ma", "Restinga-Smir", "Rhamna", "Ribat Al Khayr", "Rich", "Rissani", "Rommani", "Sabaa Aiyoun", "Safi", "Saïdia", "Saka", "Salé", "Sebt El Maârif", "Sebt Gzoula", "Sefrou", "Selouane", "Settat", "Shoul", "Sidi Allal El Bahraoui", "Sidi Allal Tazi", "Sidi Bennour", "Sidi Bibi", "Sidi Bou Othmane", "Sidi Bouknadel", "Sidi Bouzid", "Sidi Ifni", "Sidi Kacem", "Sidi Kaouki", "Sidi Moktar", "Sidi Rahhal", "Sidi Rahal", "Sidi Slimane", "Sidi Smaïl", "Sidi Taibi", "Sidi Yahia El Gharb", "Skhirat", "Skoura", "Smara", "Souk El Arbaa", "Souk Sebt Oulad Nemma", "Souq Sebt", "Tabounte", "Tafoughalt", "Tafraoute", "Taghazout", "Taghjijt", "Tagzirt", "Tahannaout", "Tahanaout", "Tahla", "Taliouine", "Tamansourt", "Tamanar", "Tamelalt", "Tamellalt", "Tameslouht", "Tamraght", "Tan-Tan", "Tanalt", "Tanant", "Tanger", "Taounate", "Taourirt", "Taouz", "Tarfaya", "Targuist", "Taroudant", "Tata", "Taza", "Tazzarine", "Témara", "Temara", "Tendrara", "Tétouan", "Tichla", "Tiflet", "Tighza", "Tiglit", "Timahdite", "Timoulay", "Tineghir", "Tinejdad", "Tinghir", "Tinmel", "Tissa", "Tissaf", "Tit Mellil", "Tiznit", "Tlat Hanchane", "Tnine Chtouka", "Touama", "Touissit", "Youssoufia", "Zag", "Zagora", "Zaïda", "Zaio", "Zaouia d'Ifrane", "Zaouiat Cheikh", "Zeghanghane", "Zinat", "Ziz", "Znata", "Zoug", "Zoumi"],
  },
  {
    code: "MZ",
    name: "Mozambique",
    flag: "🇲🇿",
    dialCode: "+258",
    cities: ["Maputo", "Matola", "Beira", "Nampula", "Chimoio", "Nacala", "Quelimane", "Tete", "Xai-Xai", "Maxixe", "Pemba", "Lichinga", "Inhambane", "Gurué", "Angoche"],
  },
  {
    code: "NA",
    name: "Namibie",
    flag: "🇳🇦",
    dialCode: "+264",
    cities: ["Windhoek", "Rundu", "Walvis Bay", "Oshakati", "Swakopmund", "Katima Mulilo", "Grootfontein", "Rehoboth", "Otjiwarongo", "Okahandja", "Keetmanshoop", "Tsumeb", "Lüderitz", "Mariental"],
  },
  {
    code: "NE",
    name: "Niger",
    flag: "🇳🇪",
    dialCode: "+227",
    cities: ["Niamey", "Zinder", "Maradi", "Agadez", "Tahoua", "Dosso", "Arlit", "Diffa", "Tillabéri", "Birni N'Konni", "Gaya", "Tessaoua", "Tanout", "Mirriah", "Magaria"],
  },
  {
    code: "NG",
    name: "Nigeria",
    flag: "🇳🇬",
    dialCode: "+234",
    cities: ["Lagos", "Kano", "Ibadan", "Abuja", "Port Harcourt", "Benin City", "Maiduguri", "Zaria", "Aba", "Jos", "Ilorin", "Oyo", "Enugu", "Abeokuta", "Onitsha", "Warri", "Sokoto", "Calabar", "Katsina", "Akure", "Bauchi", "Ebute Ikorodu", "Makurdi", "Minna", "Effon-Alaiye"],
  },
  {
    code: "RW",
    name: "Rwanda",
    flag: "🇷🇼",
    dialCode: "+250",
    cities: ["Kigali", "Butare", "Gitarama", "Ruhengeri", "Gisenyi", "Byumba", "Cyangugu", "Nyanza", "Kibungo", "Rwamagana"],
  },
  {
    code: "ST",
    name: "Sao Tomé-et-Príncipe",
    flag: "🇸🇹",
    dialCode: "+239",
    cities: ["São Tomé", "Santo António", "Neves", "Santana", "Trindade", "Santa Cruz", "Guadalupe", "Pantufo"],
  },
  {
    code: "SN",
    name: "Sénégal",
    flag: "🇸🇳",
    dialCode: "+221",
    cities: ["Dakar", "Pikine", "Touba", "Thiès", "Rufisque", "Kaolack", "M'Bour", "Ziguinchor", "Saint-Louis", "Diourbel", "Louga", "Tambacounda", "Richard-Toll", "Kolda", "Mbacké", "Tivaouane", "Joal-Fadiouth", "Fatick", "Bignona", "Kaffrine"],
  },
  {
    code: "SC",
    name: "Seychelles",
    flag: "🇸🇨",
    dialCode: "+248",
    cities: ["Victoria", "Anse Boileau", "Beau Vallon", "Anse Royale", "Cascade", "Takamaka", "Port Glaud", "Baie Lazare"],
  },
  {
    code: "SL",
    name: "Sierra Leone",
    flag: "🇸🇱",
    dialCode: "+232",
    cities: ["Freetown", "Bo", "Kenema", "Makeni", "Koidu", "Lunsar", "Port Loko", "Kabala", "Magburaka", "Waterloo"],
  },
  {
    code: "SO",
    name: "Somalie",
    flag: "🇸🇴",
    dialCode: "+252",
    cities: ["Mogadiscio", "Hargeisa", "Berbera", "Kismayo", "Merca", "Jamaame", "Baidoa", "Burao", "Bosaso", "Galkayo"],
  },
  {
    code: "ZA",
    name: "Afrique du Sud",
    flag: "🇿🇦",
    dialCode: "+27",
    cities: ["Johannesburg", "Le Cap", "Durban", "Pretoria", "Port Elizabeth", "Bloemfontein", "East London", "Nelspruit", "Kimberley", "Polokwane", "Rustenburg", "Pietermaritzburg", "Benoni", "Tembisa", "Soweto", "Centurion", "Stellenbosch", "George", "Upington", "Knysna"],
  },
  {
    code: "SS",
    name: "Soudan du Sud",
    flag: "🇸🇸",
    dialCode: "+211",
    cities: ["Djouba", "Malakal", "Wau", "Yei", "Aweil", "Bor", "Rumbek", "Bentiu", "Torit", "Kuajok"],
  },
  {
    code: "SD",
    name: "Soudan",
    flag: "🇸🇩",
    dialCode: "+249",
    cities: ["Khartoum", "Omdurman", "Port-Soudan", "Kassala", "Nyala", "Kosti", "El Obeid", "Wad Medani", "Al-Qadarif", "El Fasher", "Atbara", "Sennar", "Rabak", "El Geneina", "Dongola"],
  },
  {
    code: "TZ",
    name: "Tanzanie",
    flag: "🇹🇿",
    dialCode: "+255",
    cities: ["Dar es Salaam", "Mwanza", "Arusha", "Dodoma", "Mbeya", "Morogoro", "Tanga", "Kahama", "Tabora", "Zanzibar", "Kigoma", "Iringa", "Mtwara", "Shinyanga", "Sumbawanga"],
  },
  {
    code: "TG",
    name: "Togo",
    flag: "🇹🇬",
    dialCode: "+228",
    cities: ["Lomé", "Sokodé", "Kara", "Kpalimé", "Atakpamé", "Bassar", "Tsévié", "Aného", "Mango", "Dapaong", "Notsé", "Vogan", "Badou", "Tabligbo"],
  },
  {
    code: "TN",
    name: "Tunisie",
    flag: "🇹🇳",
    dialCode: "+216",
    cities: ["Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte", "Gabès", "Ariana", "Gafsa", "Monastir", "Ben Arous", "Kasserine", "Médenine", "Nabeul", "Tataouine", "Béja", "Jendouba", "El Kef", "Mahdia", "Sidi Bouzid", "Hammamet", "Djerba"],
  },
  {
    code: "UG",
    name: "Ouganda",
    flag: "🇺🇬",
    dialCode: "+256",
    cities: ["Kampala", "Gulu", "Lira", "Mbarara", "Jinja", "Bwizibwera", "Mbale", "Mukono", "Kasese", "Masaka", "Entebbe", "Njeru", "Kitgum", "Arua", "Soroti"],
  },
  {
    code: "ZM",
    name: "Zambie",
    flag: "🇿🇲",
    dialCode: "+260",
    cities: ["Lusaka", "Kitwe", "Ndola", "Kabwe", "Chingola", "Mufulira", "Livingstone", "Luanshya", "Kasama", "Chipata", "Solwezi", "Mansa", "Mongu", "Choma", "Kalulushi"],
  },
  {
    code: "ZW",
    name: "Zimbabwe",
    flag: "🇿🇼",
    dialCode: "+263",
    cities: ["Harare", "Bulawayo", "Chitungwiza", "Mutare", "Gweru", "Epworth", "Kwekwe", "Kadoma", "Masvingo", "Chinhoyi", "Marondera", "Norton", "Chegutu", "Bindura", "Victoria Falls"],
  },

  // Europe
  {
    code: "AL",
    name: "Albanie",
    flag: "🇦🇱",
    dialCode: "+355",
    cities: ["Tirana", "Durrës", "Vlorë", "Elbasan", "Shkodër", "Fier", "Kamëz", "Korçë", "Berat", "Lushnjë", "Kavajë", "Pogradec", "Laç", "Gjirokastër", "Sarandë"],
  },
  {
    code: "DE",
    name: "Allemagne",
    flag: "🇩🇪",
    dialCode: "+49",
    cities: ["Berlin", "Hambourg", "Munich", "Cologne", "Francfort", "Stuttgart", "Düsseldorf", "Dortmund", "Essen", "Leipzig", "Brême", "Dresde", "Hanovre", "Nuremberg", "Duisbourg", "Bochum", "Wuppertal", "Bielefeld", "Bonn", "Münster", "Karlsruhe", "Mannheim", "Augsbourg", "Wiesbaden", "Mönchengladbach"],
  },
  {
    code: "AD",
    name: "Andorre",
    flag: "🇦🇩",
    dialCode: "+376",
    cities: ["Andorre-la-Vieille", "Escaldes-Engordany", "Encamp", "Sant Julià de Lòria", "La Massana", "Santa Coloma", "Ordino", "Canillo", "Arinsal", "Pas de la Casa"],
  },
  {
    code: "AT",
    name: "Autriche",
    flag: "🇦🇹",
    dialCode: "+43",
    cities: ["Vienne", "Graz", "Linz", "Salzbourg", "Innsbruck", "Klagenfurt", "Villach", "Wels", "Sankt Pölten", "Dornbirn", "Wiener Neustadt", "Steyr", "Feldkirch", "Bregenz", "Leonding"],
  },
  {
    code: "BE",
    name: "Belgique",
    flag: "🇧🇪",
    dialCode: "+32",
    cities: ["Aarschot", "Affligem", "Alken", "Alost", "Amay", "Andenne", "Anderlecht", "Angleur", "Ans", "Antoing", "Anvers", "Arendonk", "Arlon", "Asse", "Ath", "Attert", "Aubange", "Aubel", "Auderghem", "Audenarde", "Aywaille", "Baelen", "Balen", "Bastogne", "Battice", "Beaumont", "Beauraing", "Beauvechain", "Beersel", "Beloeil", "Berchem", "Berchem-Sainte-Agathe", "Beringen", "Berlaar", "Berloz", "Bernissart", "Bertem", "Bertogne", "Bertrix", "Beveren", "Bever", "Beyne-Heusay", "Bierbeek", "Bièvre", "Bilzen", "Binche", "Blankenberge", "Boechout", "Boom", "Boortmeerbeek", "Borgerhout", "Borgloon", "Bouillon", "Boussu", "Boutersem", "Braine-l'Alleud", "Braine-le-Château", "Braine-le-Comte", "Braives", "Brasschaat", "Bree", "Bressoux", "Bruges", "Brugelette", "Brunehaut", "Bruxelles", "Burdinne", "Celles", "Chapelle-lez-Herlaimont", "Charleroi", "Chastre", "Châtelet", "Chaudfontaine", "Chaumont-Gistoux", "Chênée", "Chièvres", "Chimay", "Chiny", "Ciney", "Colfontaine", "Comines-Warneton", "Courcelles", "Court-Saint-Étienne", "Courtrai", "Couvin", "Crisnée", "Dalhem", "Daverdisse", "De Pinte", "Deerlijk", "Deinze", "Dessel", "Destelbergen", "Deurne", "Diepenbeek", "Diest", "Dilbeek", "Dilsen-Stokkem", "Dinant", "Dixmude", "Donceel", "Dour", "Drogenbos", "Durbuy", "Écaussinnes", "Edegem", "Eeklo", "Ellezelles", "Embourg", "Engis", "Enghien", "Érezée", "Erquelinnes", "Esneux", "Essen", "Estaimpuis", "Étalle", "Etterbeek", "Eupen", "Evere", "Evergem", "Faimes", "Farciennes", "Fauvillers", "Fexhe-le-Haut-Clocher", "Flémalle", "Fléron", "Fleurus", "Florenville", "Florennes", "Fontaine-l'Évêque", "Forest", "Fosses-la-Ville", "Fourons", "Frameries", "Frasnes-lez-Anvaing", "Froidchapelle", "Furnes", "Galmaarden", "Gand", "Ganshoren", "Gedinne", "Geel", "Geer", "Gembloux", "Genappe", "Genk", "Gingelom", "Gooik", "Gouvy", "Grâce-Hollogne", "Grammont", "Grez-Doiceau", "Grimbergen", "Haacht", "Habay", "Hal", "Halle", "Ham", "Hamme", "Hannut", "Harelbeke", "Hasselt", "Hélécine", "Herbeumont", "Herentals", "Herk-de-Stad", "Herne", "Héron", "Herstal", "Herve", "Heusden-Zolder", "Hoboken", "Hoeilaart", "Hoeselt", "Holsbeek", "Honnelles", "Hotton", "Houffalize", "Houthalen-Helchteren", "Hove", "Huldenberg", "Huy", "Incourt", "Ittre", "Ixelles", "Izegem", "Jalhay", "Jette", "Jodoigne", "Jupille-sur-Meuse", "Jurbise", "Kalmthout", "Kampenhout", "Kapellen", "Kapelle-op-den-Bos", "Knokke-Heist", "Koekelberg", "Koksijde", "Kontich", "Kortessem", "Kruibeke", "La Calamine", "La Hulpe", "La Louvière", "La Panne", "La Roche-en-Ardenne", "Laarne", "Lanaken", "Landen", "Lasne", "Léau", "Léglise", "Lennik", "Lens", "Leopoldsburg", "Lessines", "Leuze-en-Hainaut", "Libin", "Libramont-Chevigny", "Liedekerke", "Liège", "Lier", "Limbourg", "Linkebeek", "Lint", "Lobbes", "Lochristi", "Lokeren", "Lommel", "Londerzeel", "Lontzen", "Louvain", "Louvain-la-Neuve", "Lubbeek", "Lummen", "Maasmechelen", "Maaseik", "Machelen", "Malines", "Malle", "Malmedy", "Manage", "Manhay", "Marche-en-Famenne", "Martelange", "Meise", "Meix-devant-Virton", "Melle", "Menin", "Merbes-le-Château", "Merelbeke", "Merksem", "Messancy", "Mettet", "Middelkerke", "Mol", "Molenbeek-Saint-Jean", "Momignies", "Mons", "Mont-de-l'Enclus", "Mont-Saint-Guibert", "Morlanwelz", "Mortsel", "Mouscron", "Musson", "Namur", "Nandrin", "Nassogne", "Neufchâteau", "Neupré", "Nieuport", "Nieuwerkerken", "Nijlen", "Ninove", "Nivelles", "Olne", "Opwijk", "Oreye", "Orp-Jauche", "Ostende", "Ottignies-Louvain-la-Neuve", "Oud-Heverlee", "Oupeye", "Overijse", "Overpelt", "Paliseul", "Pecq", "Peer", "Pepingen", "Pepinster", "Péruwelz", "Perwez", "Philippeville", "Plombières", "Pont-à-Celles", "Poperinge", "Putte", "Quaregnon", "Quévy", "Quiévrain", "Raeren", "Ramillies", "Ranst", "Rebecq", "Remicourt", "Renaix", "Rendeux", "Retie", "Riemst", "Rixensart", "Rochefort", "Rocourt", "Roosdaal", "Rotselaar", "Roulers", "Rumes", "Saint-Ghislain", "Saint-Gilles", "Saint-Hubert", "Saint-Josse-ten-Noode", "Saint-Léger", "Saint-Nicolas", "Saint-Ode", "Sainte-Ode", "Sambreville", "Schaerbeek", "Schoten", "Seneffe", "Seraing", "Silly", "Sint-Genesius-Rode", "Sint-Martens-Latem", "Sint-Pieters-Leeuw", "Sint-Truiden", "Sivry-Rance", "Soignies", "Soumagne", "Spa", "Sprimont", "Stabroek", "Stavelot", "Steenokkerzeel", "Stekene", "Stoumont", "Tamise", "Tellin", "Tenneville", "Termonde", "Ternat", "Tervuren", "Tessenderlo", "Theux", "Thimister-Clermont", "Thuin", "Tielt", "Tilff", "Tintigny", "Tirlemont", "Tongres", "Torhout", "Tournai", "Trois-Ponts", "Trooz", "Tubize", "Turnhout", "Uccle", "Vaux-sur-Sûre", "Verviers", "Vielsalm", "Villers-la-Ville", "Villers-le-Bouillet", "Vilvorde", "Viroinval", "Virton", "Visé", "Voeren", "Vremde", "Vresse-sur-Semois", "Waarschoot", "Wachtebeke", "Walcourt", "Walhain", "Wandre", "Wanze", "Waregem", "Waremme", "Watermael-Boitsfort", "Waterloo", "Wavre", "Welkenraedt", "Wellin", "Wemmel", "Wetteren", "Wevelgem", "Wilrijk", "Woluwe-Saint-Lambert", "Woluwe-Saint-Pierre", "Wuustwezel", "Ypres", "Zaventem", "Zeebruges", "Zele", "Zelzate", "Zemst", "Zoersel", "Zonhoven", "Zottegem", "Zoutleeuw", "Zwevegem"],
  },
  {
    code: "BY",
    name: "Biélorussie",
    flag: "🇧🇾",
    dialCode: "+375",
    cities: ["Minsk", "Gomel", "Moguilev", "Vitebsk", "Grodno", "Brest", "Bobrouïsk", "Baranavichy", "Barysaw", "Pinsk", "Orcha", "Mazyr", "Salihorsk", "Navapolatsk", "Lida"],
  },
  {
    code: "BA",
    name: "Bosnie-Herzégovine",
    flag: "🇧🇦",
    dialCode: "+387",
    cities: ["Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar", "Bijeljina", "Brčko", "Bihać", "Prijedor", "Trebinje", "Doboj", "Cazin", "Bugojno", "Konjic", "Livno"],
  },
  {
    code: "BG",
    name: "Bulgarie",
    flag: "🇧🇬",
    dialCode: "+359",
    cities: ["Sofia", "Plovdiv", "Varna", "Bourgas", "Ruse", "Stara Zagora", "Pleven", "Sliven", "Dobrich", "Shumen", "Pernik", "Haskovo", "Yambol", "Pazardzhik", "Blagoevgrad"],
  },
  {
    code: "HR",
    name: "Croatie",
    flag: "🇭🇷",
    dialCode: "+385",
    cities: ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar", "Pula", "Slavonski Brod", "Karlovac", "Varaždin", "Šibenik", "Sisak", "Dubrovnik", "Bjelovar", "Koprivnica", "Vinkovci"],
  },
  {
    code: "DK",
    name: "Danemark",
    flag: "🇩🇰",
    dialCode: "+45",
    cities: ["Copenhague", "Aarhus", "Odense", "Aalborg", "Frederiksberg", "Esbjerg", "Randers", "Kolding", "Horsens", "Vejle", "Roskilde", "Herning", "Hørsholm", "Helsingør", "Silkeborg"],
  },
  {
    code: "ES",
    name: "Espagne",
    flag: "🇪🇸",
    dialCode: "+34",
    cities: ["Madrid", "Barcelone", "Valence", "Séville", "Saragosse", "Malaga", "Murcie", "Palma de Majorque", "Las Palmas", "Bilbao", "Alicante", "Cordoue", "Valladolid", "Vigo", "Gijón", "L'Hospitalet", "La Corogne", "Grenade", "Vitoria-Gasteiz", "Elche", "Santa Cruz de Tenerife", "Oviedo", "Badalona", "Carthagène", "Terrassa"],
  },
  {
    code: "EE",
    name: "Estonie",
    flag: "🇪🇪",
    dialCode: "+372",
    cities: ["Tallinn", "Tartu", "Narva", "Pärnu", "Kohtla-Järve", "Viljandi", "Rakvere", "Maardu", "Sillamäe", "Kuressaare", "Valga", "Võru", "Jõhvi", "Haapsalu", "Keila"],
  },
  {
    code: "FI",
    name: "Finlande",
    flag: "🇫🇮",
    dialCode: "+358",
    cities: ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku", "Jyväskylä", "Lahti", "Kuopio", "Pori", "Kouvola", "Joensuu", "Lappeenranta", "Hämeenlinna", "Vaasa", "Rovaniemi", "Seinäjoki", "Mikkeli", "Kotka", "Salo"],
  },
  {
    code: "FR",
    name: "France",
    flag: "🇫🇷",
    dialCode: "+33",
    cities: ["Agde", "Agen", "Aigues-Mortes", "Aix-en-Provence", "Aix-les-Bains", "Ajaccio", "Albertville", "Albi", "Alençon", "Aléria", "Alès", "Allonnes", "Amboise", "Amiens", "Andernos-les-Bains", "Angers", "Anglet", "Angoulême", "Annecy", "Annemasse", "Antibes", "Antony", "Anzin", "Arcachon", "Argenteuil", "Arles", "Armentières", "Arras", "Asnières-sur-Seine", "Athis-Mons", "Aubagne", "Aubervilliers", "Auch", "Audincourt", "Aulnay-sous-Bois", "Auray", "Aurillac", "Autun", "Auxerre", "Avallon", "Avignon", "Avranches", "Bagneux", "Baie-Mahault", "Bailleul", "Ballan-Miré", "Balma", "Bandraboua", "Bar-le-Duc", "Barentin", "Bastia", "Bayeux", "Bayonne", "Beaune", "Beauvais", "Belfort", "Bergerac", "Bernay", "Besançon", "Béthune", "Betton", "Bezons", "Béziers", "Biarritz", "Biguglia", "Bischheim", "Blagnac", "Blois", "Bobigny", "Bois-Guillaume", "Bolbec", "Bondy", "Bonifacio", "Bordeaux", "Borgo", "Bouguenais", "Boulogne-Billancourt", "Boulogne-sur-Mer", "Bourg-en-Bresse", "Bourges", "Bourgoin-Jallieu", "Brest", "Briançon", "Brive-la-Gaillarde", "Bron", "Bruay-la-Buissière", "Bruz", "Cabourg", "Cachan", "Caen", "Cagnes-sur-Mer", "Cahors", "Calais", "Caluire-et-Cuire", "Calvi", "Cambrai", "Cannes", "Capesterre-Belle-Eau", "Carcassonne", "Cargèse", "Carnac", "Carquefou", "Carpentras", "Carvin", "Castanet-Tolosan", "Castelnau-le-Lez", "Castres", "Cayenne", "Cenon", "Cergy", "Cervione", "Cesson-Sévigné", "Challans", "Chalon-sur-Saône", "Châlons-en-Champagne", "Chamalières", "Chambéry", "Chambray-lès-Tours", "Champigny-sur-Marne", "Changé", "Chantepie", "Charleville-Mézières", "Chartres", "Chartres-de-Bretagne", "Château-Gontier", "Châteauroux", "Châtellerault", "Châtenay-Malabry", "Châtillon", "Chelles", "Chenôve", "Cherbourg-en-Cotentin", "Chevigny-Saint-Sauveur", "Chinon", "Cholet", "Clamecy", "Clamart", "Cléon", "Clermont-Ferrand", "Clichy", "Cognac", "Colombes", "Colomiers", "Compiègne", "Concarneau", "Conflans-Sainte-Honorine", "Corbeil-Essonnes", "Corte", "Cosne-Cours-sur-Loire", "Couëron", "Coulaines", "Cournon-d'Auvergne", "Courseulles-sur-Mer", "Coutances", "Creil", "Créteil", "Creutzwald", "Croix", "Cugnaux", "Dax", "Deauville", "Décines-Charpieu", "Decize", "Dembeni", "Denain", "Déols", "Déville-lès-Rouen", "Dieppe", "Digne-les-Bains", "Digoin", "Dijon", "Dinan", "Dinard", "Dole", "Douai", "Douarnenez", "Draguignan", "Drancy", "Draveil", "Dreux", "Ducos", "Dumbéa", "Dunkerque", "Dzaoudzi", "Échirolles", "Élancourt", "Elbeuf", "Épernay", "Épinal", "Épinay-sur-Seine", "Ermont", "Eu", "Évry-Courcouronnes", "Évreux", "Eysines", "Faa'a", "Faches-Thumesnil", "Fameck", "Fécamp", "Figari", "Firminy", "Fleury-les-Aubrais", "Flers", "Floirac", "Foix", "Fondettes", "Fontaine", "Fontaine-lès-Dijon", "Fontenay-le-Comte", "Fontenay-sous-Bois", "Forbach", "Fort-de-France", "Fougères", "Fourmies", "Franconville", "Fréjus", "Frontignan", "Furiani", "Gagny", "Gap", "Garges-lès-Gonesse", "Gennevilliers", "Gérardmer", "Ghisonaccia", "Gien", "Gisors", "Givors", "Goussainville", "Gradignan", "Granville", "Grasse", "Graulhet", "Gray", "Grenoble", "Guebwiller", "Guérande", "Guéret", "Guidel", "Guingamp", "Gujan-Mestras", "Haguenau", "Halluin", "Haubourdin", "Hayange", "Hazebrouck", "Hem", "Hendaye", "Hénin-Beaumont", "Hennebont", "Héricourt", "Hérouville-Saint-Clair", "Honfleur", "Houilles", "Hyères", "Illkirch-Graffenstaden", "Issoire", "Issoudun", "Issy-les-Moulineaux", "Istres", "Ivry-sur-Seine", "Jacou", "Joigny", "Josselin", "Joué-lès-Tours", "Koné", "Koungou", "Kourou", "La Baule-Escoublac", "La Chapelle-Saint-Mesmin", "La Chapelle-sur-Erdre", "La Châtre", "La Ciotat", "La Courneuve", "La Ferté-Bernard", "La Flèche", "La Garde", "La Grande-Motte", "La Madeleine", "La Possession", "La Riche", "La Roche-sur-Yon", "La Rochelle", "La Seyne-sur-Mer", "La Teste-de-Buch", "La Trinité", "Lamballe", "Lambersart", "Lamotte-Beuvron", "Landerneau", "Lanester", "Lannion", "Laon", "Larmor-Plage", "Lattes", "Laval", "Lavaur", "Le Blanc", "Le Blanc-Mesnil", "Le Bouscat", "Le Cannet", "Le Crès", "Le Creusot", "Le François", "Le Gosier", "Le Grand-Quevilly", "Le Grau-du-Roi", "Le Havre", "Le Lamentin", "Le Mans", "Le Moule", "Le Petit-Quevilly", "Le Port", "Le Puy-en-Velay", "Le Robert", "Le Tampon", "Lecci", "Lens", "Les Abymes", "Les Andelys", "Les Avirons", "Les Sables-d'Olonne", "L'Étang-Salé", "Levallois-Perret", "Lèves", "Libourne", "Liévin", "Lille", "Lillebonne", "Limoges", "Lingolsheim", "Lisieux", "Livry-Gargan", "L'Île-Rousse", "Loches", "Locminé", "Lomme", "Longvic", "Lons", "Lons-le-Saunier", "Lorient", "Lormont", "Louhans", "Lourdes", "Louviers", "Lucciana", "Lucé", "Luçon", "Lunel", "Lunéville", "L'Union", "Luxeuil-les-Bains", "Lyon", "Mâcon", "Macouria", "Mahina", "Mainvilliers", "Maisons-Alfort", "Malakoff", "Mamers", "Mamoudzou", "Mandelieu-la-Napoule", "Manosque", "Mantes-la-Jolie", "Marcq-en-Barœul", "Marignane", "Marly", "Maromme", "Marseille", "Martigues", "Massy", "Matoury", "Maubeuge", "Mauguio", "Mayenne", "Mazamet", "Meaux", "Menton", "Mer", "Mérignac", "Metz", "Meyzieu", "Migennes", "Millau", "Miramas", "Molsheim", "Mondeville", "Mons-en-Barœul", "Montargis", "Montauban", "Montbéliard", "Montceau-les-Mines", "Mont-de-Marsan", "Mont-Dore", "Montélimar", "Montgermont", "Montigny-lès-Metz", "Montluçon", "Montpellier", "Montreuil", "Montrouge", "Mont-Saint-Aignan", "Mordelles", "Morlaix", "Morne-à-l'Eau", "Moulins", "Mulhouse", "Muret", "Nancy", "Nanterre", "Nantes", "Narbonne", "Neuilly-sur-Seine", "Nevers", "Nice", "Nîmes", "Niort", "Nogent-le-Rotrou", "Noisy-le-Grand", "Nort-sur-Erdre", "Nouméa", "Obernai", "Olivet", "Oloron-Sainte-Marie", "Orange", "Orléans", "Ormes", "Orvault", "Ouistreham", "Oullins", "Oyonnax", "Pacé", "Paea", "Païta", "Palaiseau", "Palavas-les-Flots", "Pamiers", "Pantin", "Papara", "Papeete", "Paray-le-Monial", "Paris", "Pau", "Penta-di-Casinca", "Périgueux", "Perros-Guirec", "Perpignan", "Pessac", "Petit-Bourg", "Pirae", "Pithiviers", "Plérin", "Ploemeur", "Ploërmel", "Pointe-à-Pitre", "Poissy", "Poitiers", "Pontarlier", "Pont-à-Mousson", "Pont-Audemer", "Pontivy", "Pontoise", "Pornic", "Porto-Vecchio", "Propriano", "Prunelli-di-Fiumorbo", "Punaauia", "Quetigny", "Quiberon", "Quimper", "Rambouillet", "Ramonville-Saint-Agne", "Redon", "Reims", "Rémire-Montjoly", "Remiremont", "Rennes", "Rezé", "Rillieux-la-Pape", "Riom", "Rivière-Pilote", "Roanne", "Rochefort", "Rodez", "Romans-sur-Isère", "Romorantin-Lanthenay", "Ronchin", "Rosny-sous-Bois", "Roubaix", "Rouen", "Royan", "Rueil-Malmaison", "Sablé-sur-Sarthe", "Saint-André", "Saint-Avold", "Saint-Avertin", "Saint-Benoît", "Saint-Brieuc", "Saint-Chamond", "Saint-Claude", "Saint-Cyr-sur-Loire", "Saint-Denis", "Saint-Dié-des-Vosges", "Saint-Dizier", "Sainte-Anne", "Sainte-Lucie-de-Porto-Vecchio", "Sainte-Luce-sur-Loire", "Sainte-Marie", "Sainte-Suzanne", "Saint-Étienne", "Saint-Étienne-du-Rouvray", "Saint-François", "Saint-Gaudens", "Saint-Germain-en-Laye", "Saint-Gervais-la-Forêt", "Saint-Herblain", "Saint-Jacques-de-la-Lande", "Saint-Jean-de-Braye", "Saint-Jean-de-la-Ruelle", "Saint-Jean-de-Luz", "Saint-Jean-de-Védas", "Saint-Joseph", "Saint-Laurent-du-Maroni", "Saint-Lô", "Saint-Louis", "Saint-Malo", "Saint-Martin-d'Hères", "Saint-Maur", "Saint-Maur-des-Fossés", "Saint-Médard-en-Jalles", "Saint-Nazaire", "Saint-Orens-de-Gameville", "Saint-Ouen-sur-Seine", "Saint-Paul", "Saint-Pierre", "Saint-Pierre-des-Corps", "Saint-Priest", "Saint-Quentin", "Saint-Raphaël", "Saint-Sébastien-sur-Loire", "Saintes", "Salbris", "Salon-de-Provence", "Saran", "Sarcelles", "Sarrebourg", "Sarreguemines", "Sartène", "Sartrouville", "Saumur", "Saverne", "Savigny-sur-Orge", "Schiltigheim", "Schœlcher", "Seclin", "Sedan", "Sélestat", "Senlis", "Sens", "Sète", "Sevran", "Seynod", "Sin-le-Noble", "Sisteron", "Six-Fours-les-Plages", "Sochaux", "Soissons", "Sommières", "Sotteville-lès-Rouen", "Stains", "Strasbourg", "Suresnes", "Talant", "Talence", "Tarbes", "Tassin-la-Demi-Lune", "Thiais", "Thionville", "Thonon-les-Bains", "Thorigné-Fouillard", "Thouaré-sur-Loire", "Tonnerre", "Toul", "Toulon", "Toulouse", "Tourcoing", "Tournefeuille", "Tournus", "Tours", "Tremblay-en-France", "Troyes", "Trouville-sur-Mer", "Tulle", "Uzès", "Valence", "Valenciennes", "Valentigney", "Vallauris", "Vandœuvre-lès-Nancy", "Vannes", "Varennes-Vauzelles", "Vaulx-en-Velin", "Vendôme", "Vénissieux", "Verdun", "Vernon", "Versailles", "Vertou", "Vesoul", "Vichy", "Vienne", "Vierzon", "Villefranche-de-Rouergue", "Villefranche-sur-Saône", "Villejuif", "Villenave-d'Ornon", "Villeneuve-d'Ascq", "Villeneuve-Saint-Georges", "Villeneuve-sur-Lot", "Villepinte", "Villeurbanne", "Vincennes", "Vineuil", "Vire Normandie", "Viry-Châtillon", "Vitré", "Vitrolles", "Vitry-le-François", "Vitry-sur-Seine", "Voiron", "Wasquehal", "Wattignies", "Wattrelos", "Wissembourg", "Woippy", "Yerres", "Yutz", "Yvetot", "Zonza"],
  },
  {
    code: "GR",
    name: "Grèce",
    flag: "🇬🇷",
    dialCode: "+30",
    cities: ["Athènes", "Thessalonique", "Patras", "Le Pirée", "Larissa", "Héraklion", "Peristeri", "Kallithea", "Acharnes", "Kalamaria", "Nikaia", "Glyfada", "Volos", "Ilio", "Ilioupoli", "Keratsini", "Nea Smyrni", "Chalandri", "Marousi", "Agios Dimitrios"],
  },
  {
    code: "HU",
    name: "Hongrie",
    flag: "🇭🇺",
    dialCode: "+36",
    cities: ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pécs", "Győr", "Nyíregyháza", "Kecskemét", "Székesfehérvár", "Szombathely", "Szolnok", "Tatabánya", "Kaposvár", "Békéscsaba", "Érd", "Veszprém", "Zalaegerszeg", "Sopron", "Eger", "Nagykanizsa"],
  },
  {
    code: "IE",
    name: "Irlande",
    flag: "🇮🇪",
    dialCode: "+353",
    cities: ["Dublin", "Cork", "Limerick", "Galway", "Waterford", "Drogheda", "Dundalk", "Swords", "Bray", "Navan", "Ennis", "Kilkenny", "Carlow", "Tralee", "Newbridge", "Portlaoise", "Mullingar", "Wexford", "Letterkenny", "Athlone"],
  },
  {
    code: "IS",
    name: "Islande",
    flag: "🇮🇸",
    dialCode: "+354",
    cities: ["Reykjavik", "Kópavogur", "Hafnarfjörður", "Akureyri", "Reykjanesbær", "Garðabær", "Mosfellsbær", "Árborg", "Akranes", "Fjarðabyggð", "Ísafjörður", "Vestmannaeyjar", "Seltjarnarnes", "Selfoss"],
  },
  {
    code: "IT",
    name: "Italie",
    flag: "🇮🇹",
    dialCode: "+39",
    cities: ["Rome", "Milan", "Naples", "Turin", "Palerme", "Gênes", "Bologne", "Florence", "Bari", "Catane", "Venise", "Vérone", "Messine", "Padoue", "Trieste", "Brescia", "Tarente", "Prato", "Parme", "Modène", "Reggio de Calabre", "Reggio d'Émilie", "Pérouse", "Livourne", "Ravenne", "Cagliari", "Foggia", "Rimini", "Salerne", "Ferrare"],
  },
  {
    code: "XK",
    name: "Kosovo",
    flag: "🇽🇰",
    dialCode: "+383",
    cities: ["Pristina", "Prizren", "Ferizaj", "Peja", "Gjakova", "Gjilan", "Mitrovica", "Podujevo", "Vushtrri", "Suhareka", "Rahovec", "Drenas", "Lipjan", "Malisheva", "Kamenica"],
  },
  {
    code: "LV",
    name: "Lettonie",
    flag: "🇱🇻",
    dialCode: "+371",
    cities: ["Riga", "Daugavpils", "Liepāja", "Jelgava", "Jūrmala", "Ventspils", "Rēzekne", "Valmiera", "Jēkabpils", "Ogre", "Tukums", "Salaspils", "Cēsis", "Kuldīga", "Olaine"],
  },
  {
    code: "LI",
    name: "Liechtenstein",
    flag: "🇱🇮",
    dialCode: "+423",
    cities: ["Vaduz", "Schaan", "Triesen", "Balzers", "Eschen", "Mauren", "Triesenberg", "Ruggell", "Gamprin", "Schellenberg", "Planken"],
  },
  {
    code: "LT",
    name: "Lituanie",
    flag: "🇱🇹",
    dialCode: "+370",
    cities: ["Vilnius", "Kaunas", "Klaipėda", "Šiauliai", "Panevėžys", "Alytus", "Marijampolė", "Mažeikiai", "Jonava", "Utena", "Kėdainiai", "Telšiai", "Tauragė", "Ukmergė", "Visaginas"],
  },
  {
    code: "LU",
    name: "Luxembourg",
    flag: "🇱🇺",
    dialCode: "+352",
    cities: ["Luxembourg", "Esch-sur-Alzette", "Differdange", "Dudelange", "Pétange", "Ettelbruck", "Diekirch", "Strassen", "Bertrange", "Belvaux", "Mamer", "Hesperange", "Schifflange", "Bettembourg", "Mersch"],
  },
  {
    code: "MK",
    name: "Macédoine du Nord",
    flag: "🇲🇰",
    dialCode: "+389",
    cities: ["Skopje", "Bitola", "Kumanovo", "Prilep", "Tetovo", "Ohrid", "Veles", "Štip", "Gostivar", "Strumica", "Kavadarci", "Kočani", "Kičevo", "Struga", "Radoviš"],
  },
  {
    code: "MT",
    name: "Malte",
    flag: "🇲🇹",
    dialCode: "+356",
    cities: ["La Valette", "Birkirkara", "Mosta", "Qormi", "Żabbar", "St. Paul's Bay", "San Ġwann", "Naxxar", "Żejtun", "Fgura", "Sliema", "Ħamrun", "Rabat", "Victoria", "Marsaskala"],
  },
  {
    code: "MD",
    name: "Moldavie",
    flag: "🇲🇩",
    dialCode: "+373",
    cities: ["Chișinău", "Tiraspol", "Bălți", "Bender", "Rîbnița", "Cahul", "Ungheni", "Soroca", "Orhei", "Dubăsari", "Comrat", "Edineț", "Ceadîr-Lunga", "Strășeni", "Căușeni"],
  },
  {
    code: "MC",
    name: "Monaco",
    flag: "🇲🇨",
    dialCode: "+377",
    cities: ["Monaco", "Monte-Carlo", "La Condamine", "Fontvieille", "Moneghetti", "Larvotto", "Saint-Roman", "La Rousse"],
  },
  {
    code: "ME",
    name: "Monténégro",
    flag: "🇲🇪",
    dialCode: "+382",
    cities: ["Podgorica", "Nikšić", "Herceg Novi", "Pljevlja", "Bijelo Polje", "Cetinje", "Bar", "Budva", "Berane", "Ulcinj", "Tivat", "Kotor", "Rožaje", "Danilovgrad", "Mojkovac"],
  },
  {
    code: "NO",
    name: "Norvège",
    flag: "🇳🇴",
    dialCode: "+47",
    cities: ["Oslo", "Bergen", "Trondheim", "Stavanger", "Drammen", "Fredrikstad", "Kristiansand", "Sandnes", "Tromsø", "Sarpsborg", "Skien", "Ålesund", "Sandefjord", "Haugesund", "Tønsberg", "Moss", "Porsgrunn", "Bodø", "Arendal", "Hamar"],
  },
  {
    code: "NL",
    name: "Pays-Bas",
    flag: "🇳🇱",
    dialCode: "+31",
    cities: ["Amsterdam", "Rotterdam", "La Haye", "Utrecht", "Eindhoven", "Tilburg", "Groningue", "Almere", "Breda", "Nimègue", "Enschede", "Haarlem", "Arnhem", "Zaanstad", "Amersfoort", "Apeldoorn", "Hoofddorp", "Maastricht", "Leyde", "Dordrecht", "Zoetermeer", "Zwolle", "Delft", "Alkmaar", "Heerlen"],
  },
  {
    code: "PL",
    name: "Pologne",
    flag: "🇵🇱",
    dialCode: "+48",
    cities: ["Varsovie", "Cracovie", "Łódź", "Wrocław", "Poznań", "Gdańsk", "Szczecin", "Bydgoszcz", "Lublin", "Białystok", "Katowice", "Gdynia", "Częstochowa", "Radom", "Sosnowiec", "Toruń", "Kielce", "Rzeszów", "Gliwice", "Zabrze", "Olsztyn", "Bielsko-Biała", "Bytom", "Zielona Góra", "Rybnik"],
  },
  {
    code: "PT",
    name: "Portugal",
    flag: "🇵🇹",
    dialCode: "+351",
    cities: ["Lisbonne", "Porto", "Vila Nova de Gaia", "Amadora", "Braga", "Setúbal", "Coimbra", "Funchal", "Almada", "Agualva-Cacém", "Queluz", "Leiria", "Viseu", "Guimarães", "Évora", "Odivelas", "Rio Tinto", "Matosinhos", "Aveiro", "Faro", "Portimão", "Póvoa de Varzim", "Vila Franca de Xira", "Santa Maria da Feira", "Barcelos"],
  },
  {
    code: "CZ",
    name: "Tchéquie",
    flag: "🇨🇿",
    dialCode: "+420",
    cities: ["Prague", "Brno", "Ostrava", "Plzeň", "Liberec", "Olomouc", "Ústí nad Labem", "České Budějovice", "Hradec Králové", "Pardubice", "Havířov", "Zlín", "Kladno", "Most", "Karviná", "Opava", "Frýdek-Místek", "Děčín", "Karlovy Vary", "Jihlava"],
  },
  {
    code: "RO",
    name: "Roumanie",
    flag: "🇷🇴",
    dialCode: "+40",
    cities: ["Bucarest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța", "Craiova", "Brașov", "Galați", "Ploiești", "Oradea", "Brăila", "Arad", "Pitești", "Sibiu", "Bacău", "Târgu Mureș", "Baia Mare", "Buzău", "Botoșani", "Satu Mare"],
  },
  {
    code: "GB",
    name: "Royaume-Uni",
    flag: "🇬🇧",
    dialCode: "+44",
    cities: ["Londres", "Birmingham", "Manchester", "Glasgow", "Liverpool", "Bristol", "Sheffield", "Leeds", "Édimbourg", "Leicester", "Coventry", "Bradford", "Cardiff", "Belfast", "Nottingham", "Kingston upon Hull", "Newcastle", "Stoke-on-Trent", "Southampton", "Derby", "Portsmouth", "Brighton", "Plymouth", "Wolverhampton", "Reading"],
  },
  {
    code: "RU",
    name: "Russie",
    flag: "🇷🇺",
    dialCode: "+7",
    cities: ["Moscou", "Saint-Pétersbourg", "Novossibirsk", "Ekaterinbourg", "Nijni Novgorod", "Kazan", "Tcheliabinsk", "Omsk", "Samara", "Rostov-sur-le-Don", "Oufa", "Krasnoïarsk", "Voronej", "Perm", "Volgograd", "Saratov", "Krasnodar", "Togliatti", "Tioumen", "Ijevsk", "Barnaoul", "Vladivostok", "Irkoutsk", "Khabarovsk", "Iaroslavl"],
  },
  {
    code: "SM",
    name: "Saint-Marin",
    flag: "🇸🇲",
    dialCode: "+378",
    cities: ["Saint-Marin", "Serravalle", "Borgo Maggiore", "Domagnano", "Fiorentino", "Acquaviva", "Faetano", "Montegiardino", "Chiesanuova"],
  },
  {
    code: "RS",
    name: "Serbie",
    flag: "🇷🇸",
    dialCode: "+381",
    cities: ["Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica", "Zrenjanin", "Pančevo", "Čačak", "Kraljevo", "Novi Pazar", "Smederevo", "Leskovac", "Valjevo", "Kruševac", "Vranje", "Šabac", "Užice", "Sombor", "Požarevac", "Pirot"],
  },
  {
    code: "SK",
    name: "Slovaquie",
    flag: "🇸🇰",
    dialCode: "+421",
    cities: ["Bratislava", "Košice", "Prešov", "Žilina", "Nitra", "Banská Bystrica", "Trnava", "Martin", "Trenčín", "Poprad", "Prievidza", "Zvolen", "Považská Bystrica", "Michalovce", "Nové Zámky"],
  },
  {
    code: "SI",
    name: "Slovénie",
    flag: "🇸🇮",
    dialCode: "+386",
    cities: ["Ljubljana", "Maribor", "Celje", "Kranj", "Velenje", "Koper", "Novo Mesto", "Ptuj", "Trbovlje", "Kamnik", "Jesenice", "Nova Gorica", "Domžale", "Škofja Loka", "Murska Sobota"],
  },
  {
    code: "SE",
    name: "Suède",
    flag: "🇸🇪",
    dialCode: "+46",
    cities: ["Stockholm", "Göteborg", "Malmö", "Uppsala", "Västerås", "Örebro", "Linköping", "Helsingborg", "Jönköping", "Norrköping", "Lund", "Umeå", "Gävle", "Borås", "Södertälje", "Eskilstuna", "Karlstad", "Halmstad", "Täby", "Växjö"],
  },
  {
    code: "CH",
    name: "Suisse",
    flag: "🇨🇭",
    dialCode: "+41",
    cities: ["Zurich", "Genève", "Bâle", "Lausanne", "Berne", "Winterthour", "Lucerne", "Saint-Gall", "Lugano", "Bienne", "Thoune", "Köniz", "La Chaux-de-Fonds", "Fribourg", "Schaffhouse", "Coire", "Neuchâtel", "Vernier", "Uster", "Sion", "Lancy", "Emmen", "Yverdon-les-Bains", "Zoug", "Montreux"],
  },
  {
    code: "UA",
    name: "Ukraine",
    flag: "🇺🇦",
    dialCode: "+380",
    cities: ["Kiev", "Kharkiv", "Odessa", "Dnipro", "Donetsk", "Zaporijia", "Lviv", "Kryvyï Rih", "Mykolaïv", "Marioupol", "Louhansk", "Vinnytsia", "Makiïvka", "Simferopol", "Kherson", "Poltava", "Tchernihiv", "Tcherkassy", "Soumy", "Jytomyr", "Horlivka", "Ivano-Frankivsk", "Krouvanka", "Ternopil", "Oujhorod"],
  },
  {
    code: "VA",
    name: "Vatican",
    flag: "🇻🇦",
    dialCode: "+379",
    cities: ["Vatican"],
  },

  // Amérique du Nord
  {
    code: "CA",
    name: "Canada",
    flag: "🇨🇦",
    dialCode: "+1",
    cities: ["Toronto", "Montréal", "Vancouver", "Calgary", "Edmonton", "Ottawa", "Winnipeg", "Québec", "Hamilton", "Kitchener", "London", "Victoria", "Halifax", "Oshawa", "Windsor", "Saskatoon", "Regina", "St. Catharines", "Kelowna", "Barrie", "Sherbrooke", "Guelph", "Abbotsford", "Kingston", "Trois-Rivières", "Moncton", "Chicoutimi", "Saint John", "Thunder Bay", "Gatineau"],
  },
  {
    code: "US",
    name: "États-Unis",
    flag: "🇺🇸",
    dialCode: "+1",
    cities: ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphie", "San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Jacksonville", "Fort Worth", "Columbus", "Indianapolis", "Charlotte", "San Francisco", "Seattle", "Denver", "Washington D.C.", "Nashville", "Boston", "El Paso", "Detroit", "Memphis", "Portland", "Oklahoma City", "Las Vegas", "Louisville", "Baltimore", "Milwaukee", "Albuquerque", "Tucson", "Fresno", "Sacramento", "Kansas City", "Atlanta", "Miami", "Raleigh", "Omaha", "Colorado Springs", "Virginia Beach", "Tampa", "Orlando", "Minneapolis", "New Orleans", "Cleveland", "Honolulu", "Anchorage"],
  },
  {
    code: "MX",
    name: "Mexique",
    flag: "🇲🇽",
    dialCode: "+52",
    cities: ["Mexico", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "León", "Juárez", "Zapopan", "Mérida", "San Luis Potosí", "Aguascalientes", "Hermosillo", "Saltillo", "Mexicali", "Culiacán", "Querétaro", "Acapulco", "Chihuahua", "Cancún", "Morelia", "Veracruz", "Durango", "Toluca", "Torreón", "Tuxtla Gutiérrez"],
  },

  // Amérique centrale
  {
    code: "BZ",
    name: "Belize",
    flag: "🇧🇿",
    dialCode: "+501",
    cities: ["Belize City", "San Ignacio", "Orange Walk Town", "Belmopan", "Dangriga", "Corozal Town", "San Pedro", "Punta Gorda", "Benque Viejo del Carmen"],
  },
  {
    code: "CR",
    name: "Costa Rica",
    flag: "🇨🇷",
    dialCode: "+506",
    cities: ["San José", "Limón", "San Francisco", "Alajuela", "Liberia", "Paraíso", "Desamparados", "San Vicente", "San Isidro", "Curridabat", "San Rafael Abajo", "Puntarenas", "Cartago", "Heredia", "Turrialba"],
  },
  {
    code: "SV",
    name: "Salvador",
    flag: "🇸🇻",
    dialCode: "+503",
    cities: ["San Salvador", "Santa Ana", "San Miguel", "Mejicanos", "Santa Tecla", "Soyapango", "Apopa", "Delgado", "San Marcos", "Ahuachapán", "San Martin", "Usulután", "Cojutepeque", "Ilopango", "Zacatecoluca"],
  },
  {
    code: "GT",
    name: "Guatemala",
    flag: "🇬🇹",
    dialCode: "+502",
    cities: ["Guatemala City", "Mixco", "Villa Nueva", "Petapa", "San Juan Sacatepéquez", "Quetzaltenango", "Villa Canales", "Escuintla", "Chinautla", "Chimaltenango", "Amatitlán", "Huehuetenango", "Puerto Barrios", "Santa Lucía Cotzumalguapa", "Coatepeque"],
  },
  {
    code: "HN",
    name: "Honduras",
    flag: "🇭🇳",
    dialCode: "+504",
    cities: ["Tegucigalpa", "San Pedro Sula", "Choloma", "La Ceiba", "El Progreso", "Comayagua", "Choluteca", "Juticalpa", "Puerto Cortés", "Danlí", "Santa Rosa de Copán", "Siguatepeque", "Tela", "Catacamas", "Tocoa"],
  },
  {
    code: "NI",
    name: "Nicaragua",
    flag: "🇳🇮",
    dialCode: "+505",
    cities: ["Managua", "León", "Masaya", "Matagalpa", "Chinandega", "Granada", "Estelí", "Tipitapa", "Jinotega", "El Viejo", "Nueva Guinea", "Juigalpa", "Bluefields", "Diriamba", "Ocotal"],
  },
  {
    code: "PA",
    name: "Panama",
    flag: "🇵🇦",
    dialCode: "+507",
    cities: ["Panama City", "San Miguelito", "Tocumen", "David", "Arraiján", "Colón", "Las Cumbres", "La Chorrera", "Pacora", "Santiago", "Chitré", "Vista Alegre", "Changuinola", "Aguadulce", "Penonomé"],
  },

  // Amérique du Sud
  {
    code: "AR",
    name: "Argentine",
    flag: "🇦🇷",
    dialCode: "+54",
    cities: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata", "San Miguel de Tucumán", "Mar del Plata", "Salta", "Santa Fe", "San Juan", "Resistencia", "Neuquén", "Santiago del Estero", "Corrientes", "Bahía Blanca", "San Salvador de Jujuy", "Posadas", "Paraná", "Formosa", "San Luis"],
  },
  {
    code: "BO",
    name: "Bolivie",
    flag: "🇧🇴",
    dialCode: "+591",
    cities: ["Santa Cruz de la Sierra", "El Alto", "La Paz", "Cochabamba", "Oruro", "Sucre", "Tarija", "Potosí", "Sacaba", "Montero", "Quillacollo", "Trinidad", "Yacuiba", "Riberalta", "Warnes"],
  },
  {
    code: "BR",
    name: "Brésil",
    flag: "🇧🇷",
    dialCode: "+55",
    cities: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza", "Belo Horizonte", "Manaus", "Curitiba", "Recife", "Porto Alegre", "Belém", "Goiânia", "Guarulhos", "Campinas", "São Luís", "São Gonçalo", "Maceió", "Duque de Caxias", "Natal", "Teresina", "São Bernardo do Campo", "Campo Grande", "Osasco", "João Pessoa", "Jaboatão dos Guararapes"],
  },
  {
    code: "CL",
    name: "Chili",
    flag: "🇨🇱",
    dialCode: "+56",
    cities: ["Santiago", "Puente Alto", "Antofagasta", "Viña del Mar", "Valparaíso", "Talcahuano", "San Bernardo", "Temuco", "Iquique", "Concepción", "Rancagua", "La Serena", "Arica", "Talca", "Chillán", "Los Ángeles", "Puerto Montt", "Coquimbo", "Osorno", "Valdivia"],
  },
  {
    code: "CO",
    name: "Colombie",
    flag: "🇨🇴",
    dialCode: "+57",
    cities: ["Bogota", "Medellín", "Cali", "Barranquilla", "Carthagène", "Cúcuta", "Soledad", "Bucaramanga", "Ibagué", "Soacha", "Santa Marta", "Villavicencio", "Bello", "Pereira", "Valledupar", "Manizales", "Buenaventura", "Pasto", "Montería", "Neiva"],
  },
  {
    code: "EC",
    name: "Équateur",
    flag: "🇪🇨",
    dialCode: "+593",
    cities: ["Guayaquil", "Quito", "Cuenca", "Santo Domingo", "Machala", "Durán", "Manta", "Portoviejo", "Loja", "Ambato", "Esmeraldas", "Quevedo", "Riobamba", "Milagro", "Ibarra", "La Libertad", "Babahoyo", "Sangolquí", "Daule", "Latacunga"],
  },
  {
    code: "GY",
    name: "Guyana",
    flag: "🇬🇾",
    dialCode: "+592",
    cities: ["Georgetown", "Linden", "New Amsterdam", "Anna Regina", "Bartica", "Skeldon", "Rosignol", "Mahaica", "Paradise", "Vreed en Hoop"],
  },
  {
    code: "PY",
    name: "Paraguay",
    flag: "🇵🇾",
    dialCode: "+595",
    cities: ["Asunción", "Ciudad del Este", "San Lorenzo", "Luque", "Capiatá", "Lambaré", "Fernando de la Mora", "Limpio", "Ñemby", "Encarnación", "Mariano Roque Alonso", "Pedro Juan Caballero", "Villa Elisa", "Caaguazú", "Coronel Oviedo"],
  },
  {
    code: "PE",
    name: "Pérou",
    flag: "🇵🇪",
    dialCode: "+51",
    cities: ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Piura", "Iquitos", "Cusco", "Huancayo", "Chimbote", "Pucallpa", "Tacna", "Juliaca", "Ica", "Sullana", "Ayacucho", "Chincha Alta", "Cajamarca", "Huánuco", "Tarapoto", "Puno"],
  },
  {
    code: "SR",
    name: "Suriname",
    flag: "🇸🇷",
    dialCode: "+597",
    cities: ["Paramaribo", "Lelydorp", "Brokopondo", "Nieuw Nickerie", "Moengo", "Meerzorg", "Mariënburg", "Wageningen", "Albina", "Groningen"],
  },
  {
    code: "UY",
    name: "Uruguay",
    flag: "🇺🇾",
    dialCode: "+598",
    cities: ["Montevideo", "Salto", "Ciudad de la Costa", "Paysandú", "Las Piedras", "Rivera", "Maldonado", "Tacuarembó", "Melo", "Mercedes", "Artigas", "Minas", "San José de Mayo", "Durazno", "Florida"],
  },
  {
    code: "VE",
    name: "Venezuela",
    flag: "🇻🇪",
    dialCode: "+58",
    cities: ["Caracas", "Maracaibo", "Valence", "Barquisimeto", "Maracay", "Ciudad Guayana", "Barcelona", "Maturín", "Petare", "Turmero", "Ciudad Bolívar", "Cumana", "Mérida", "Barinas", "Cabimas", "Los Teques", "Puerto La Cruz", "Coro", "Punto Fijo", "San Cristóbal"],
  },

  // Caraïbes
  {
    code: "AG",
    name: "Antigua-et-Barbuda",
    flag: "🇦🇬",
    dialCode: "+1268",
    cities: ["Saint John's", "All Saints", "Liberta", "Potter's Village", "Bolands", "Swetes", "Parham", "Freetown", "English Harbour Town"],
  },
  {
    code: "BS",
    name: "Bahamas",
    flag: "🇧🇸",
    dialCode: "+1242",
    cities: ["Nassau", "Lucaya", "Freeport", "West End", "Coopers Town", "Marsh Harbour", "Freetown", "High Rock", "Andros Town", "Clarence Town"],
  },
  {
    code: "BB",
    name: "Barbade",
    flag: "🇧🇧",
    dialCode: "+1246",
    cities: ["Bridgetown", "Speightstown", "Oistins", "Bathsheba", "Holetown", "Crane", "Bulkeley", "Greenland"],
  },
  {
    code: "CU",
    name: "Cuba",
    flag: "🇨🇺",
    dialCode: "+53",
    cities: ["La Havane", "Santiago de Cuba", "Camagüey", "Holguín", "Guantánamo", "Santa Clara", "Las Tunas", "Bayamo", "Cienfuegos", "Pinar del Río", "Matanzas", "Ciego de Ávila", "Sancti Spíritus", "Manzanillo", "Cárdenas"],
  },
  {
    code: "DM",
    name: "Dominique",
    flag: "🇩🇲",
    dialCode: "+1767",
    cities: ["Roseau", "Portsmouth", "Marigot", "Berekua", "Mahaut", "Saint Joseph", "Wesley", "Soufrière", "Castle Bruce", "La Plaine"],
  },
  {
    code: "GD",
    name: "Grenade",
    flag: "🇬🇩",
    dialCode: "+1473",
    cities: ["Saint George's", "Gouyave", "Grenville", "Victoria", "Sauteurs", "Saint David's", "Hillsborough"],
  },
  {
    code: "HT",
    name: "Haïti",
    flag: "🇭🇹",
    dialCode: "+509",
    cities: ["Port-au-Prince", "Carrefour", "Delmas", "Pétionville", "Cap-Haïtien", "Gonaïves", "Saint-Marc", "Les Cayes", "Port-de-Paix", "Jacmel", "Léogâne", "Kenscoff", "Verrettes", "Limbé", "Jérémie"],
  },
  {
    code: "JM",
    name: "Jamaïque",
    flag: "🇯🇲",
    dialCode: "+1876",
    cities: ["Kingston", "Spanish Town", "Portmore", "Montego Bay", "May Pen", "Mandeville", "Savanna-la-Mar", "Old Harbour", "Linstead", "Half Way Tree", "Ocho Rios", "Negril", "Port Antonio", "Morant Bay", "Santa Cruz"],
  },
  {
    code: "DO",
    name: "République dominicaine",
    flag: "🇩🇴",
    dialCode: "+1809",
    cities: ["Saint-Domingue", "Santiago de los Caballeros", "Santo Domingo Este", "Santo Domingo Norte", "Santo Domingo Oeste", "San Pedro de Macorís", "La Romana", "San Cristóbal", "Puerto Plata", "San Francisco de Macorís", "Higüey", "La Vega", "Bonao", "Moca", "Azua de Compostela"],
  },
  {
    code: "KN",
    name: "Saint-Kitts-et-Nevis",
    flag: "🇰🇳",
    dialCode: "+1869",
    cities: ["Basseterre", "Charlestown", "Sandy Point Town", "Dieppe Bay Town", "Saint Paul's", "Middle Island", "Old Road Town", "Cayon", "Newcastle", "Gingerland"],
  },
  {
    code: "LC",
    name: "Sainte-Lucie",
    flag: "🇱🇨",
    dialCode: "+1758",
    cities: ["Castries", "Vieux Fort", "Micoud", "Soufrière", "Dennery", "Gros Islet", "Laborie", "Anse la Raye", "Choiseul", "Canaries"],
  },
  {
    code: "VC",
    name: "Saint-Vincent-et-les-Grenadines",
    flag: "🇻🇨",
    dialCode: "+1784",
    cities: ["Kingstown", "Georgetown", "Byera Village", "Biabou", "Barrouallie", "Chateaubelair", "Layou", "Port Elizabeth"],
  },
  {
    code: "TT",
    name: "Trinité-et-Tobago",
    flag: "🇹🇹",
    dialCode: "+1868",
    cities: ["Port-d'Espagne", "Chaguanas", "San Fernando", "Mon Repos", "Couva", "Sangre Grande", "Point Fortin", "Penal", "Tunapuna", "Arima", "Scarborough", "Princes Town", "La Romaine", "Rio Claro", "Diego Martin"],
  },

  // Asie
  {
    code: "AF",
    name: "Afghanistan",
    flag: "🇦🇫",
    dialCode: "+93",
    cities: ["Kaboul", "Kandahar", "Herat", "Mazar-e-Charif", "Djalalabad", "Kondoz", "Ghazni", "Balkh", "Baghlan", "Gardez", "Khost", "Lashkar Gah", "Taloqan", "Poul-e-Khomri", "Charikar"],
  },
  {
    code: "SA",
    name: "Arabie Saoudite",
    flag: "🇸🇦",
    dialCode: "+966",
    cities: ["Riyad", "Djeddah", "La Mecque", "Médine", "Dammam", "Taif", "Tabuk", "Buraydah", "Khamis Mushait", "Abha", "Al Hufuf", "Al Mubarraz", "Najran", "Jubail", "Yanbu", "Al Khobar", "Jazan", "Hail", "Al Qatif", "Kharj"],
  },
  {
    code: "AM",
    name: "Arménie",
    flag: "🇦🇲",
    dialCode: "+374",
    cities: ["Erevan", "Gyumri", "Vanadzor", "Vagharshapat", "Hrazdan", "Abovyan", "Kapan", "Armavir", "Gavar", "Artashat", "Charentsavan", "Ijevan", "Goris", "Masis", "Sevan"],
  },
  {
    code: "AZ",
    name: "Azerbaïdjan",
    flag: "🇦🇿",
    dialCode: "+994",
    cities: ["Bakou", "Gandja", "Soumqayıt", "Mingatchevir", "Lankaran", "Chirvan", "Nakhitchevan", "Chaki", "Yevlakh", "Khatchmaz", "Quba", "Chamakhi", "Zaqatala", "Qobustan", "Beylagan"],
  },
  {
    code: "BH",
    name: "Bahreïn",
    flag: "🇧🇭",
    dialCode: "+973",
    cities: ["Manama", "Muharraq", "Riffa", "Hamad Town", "A'ali", "Isa Town", "Sitra", "Budaiya", "Jidhafs", "Al-Malikiyah"],
  },
  {
    code: "BD",
    name: "Bangladesh",
    flag: "🇧🇩",
    dialCode: "+880",
    cities: ["Dacca", "Chittagong", "Khulna", "Rajshahi", "Sylhet", "Rangpur", "Comilla", "Gazipur", "Narayanganj", "Mymensingh", "Barisal", "Tongi", "Bogra", "Cox's Bazar", "Jessore", "Dinajpur", "Brahmanbaria", "Narsingdi", "Savar", "Tangail"],
  },
  {
    code: "BT",
    name: "Bhoutan",
    flag: "🇧🇹",
    dialCode: "+975",
    cities: ["Thimphou", "Phuntsholing", "Punakha", "Paro", "Gelephu", "Samdrup Jongkhar", "Wangdue Phodrang", "Mongar", "Trashigang", "Bumthang"],
  },
  {
    code: "BN",
    name: "Brunei",
    flag: "🇧🇳",
    dialCode: "+673",
    cities: ["Bandar Seri Begawan", "Kuala Belait", "Seria", "Tutong", "Bangar", "Jerudong", "Muara", "Temburong", "Pekan Tutong"],
  },
  {
    code: "KH",
    name: "Cambodge",
    flag: "🇰🇭",
    dialCode: "+855",
    cities: ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville", "Poipet", "Ta Khmau", "Kampong Cham", "Pursat", "Kampong Speu", "Prey Veng", "Kratié", "Kampong Chhnang", "Svay Rieng", "Kampot", "Koh Kong"],
  },
  {
    code: "CN",
    name: "Chine",
    flag: "🇨🇳",
    dialCode: "+86",
    cities: ["Shanghai", "Pékin", "Canton", "Shenzhen", "Chongqing", "Tianjin", "Wuhan", "Chengdu", "Dongguan", "Nanjing", "Hong Kong", "Xi'an", "Shenyang", "Hangzhou", "Foshan", "Harbin", "Dalian", "Qingdao", "Zhengzhou", "Jinan", "Changsha", "Kunming", "Taiyuan", "Changchun", "Nanchang", "Fuzhou", "Xiamen", "Nanning", "Guiyang", "Suzhou"],
  },
  {
    code: "KP",
    name: "Corée du Nord",
    flag: "🇰🇵",
    dialCode: "+850",
    cities: ["Pyongyang", "Hamhung", "Chongjin", "Nampo", "Wonsan", "Sinuiju", "Kaesong", "Sariwon", "Haeju", "Kanggye", "Rason", "Hyesan", "Kimchaek", "Hungnam", "Anju"],
  },
  {
    code: "KR",
    name: "Corée du Sud",
    flag: "🇰🇷",
    dialCode: "+82",
    cities: ["Séoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Suwon", "Ulsan", "Changwon", "Goyang", "Yongin", "Seongnam", "Bucheon", "Ansan", "Cheongju", "Anyang", "Namyangju", "Hwaseong", "Jeonju", "Cheonan", "Pohang", "Gimhae", "Uijeongbu", "Jeju", "Asan"],
  },
  {
    code: "AE",
    name: "Émirats Arabes Unis",
    flag: "🇦🇪",
    dialCode: "+971",
    cities: ["Dubaï", "Abou Dabi", "Charjah", "Al Ain", "Ajman", "Ras el Khaïmah", "Fujaïrah", "Oumm al Qaïwaïn", "Khor Fakkan", "Dibba Al-Fujairah", "Dibba Al-Hisn", "Al Dhaid", "Jebel Ali", "Madinat Zayed", "Ruwais"],
  },
  {
    code: "GE",
    name: "Géorgie",
    flag: "🇬🇪",
    dialCode: "+995",
    cities: ["Tbilissi", "Batoumi", "Koutaïssi", "Roustavi", "Gori", "Soukhoumi", "Zougdidi", "Poti", "Tskhinvali", "Samtredia", "Khachouri", "Senaki", "Marneuli", "Telavi", "Akhaltsikhe"],
  },
  {
    code: "IN",
    name: "Inde",
    flag: "🇮🇳",
    dialCode: "+91",
    cities: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", "Kolkata", "Ahmedabad", "Pune", "Surat", "Jaipur", "Lucknow", "Kanpur", "Nagpur", "Indore", "Thane", "Bhopal", "Visakhapatnam", "Patna", "Vadodara", "Ghaziabad", "Ludhiana", "Agra", "Nashik", "Faridabad", "Meerut", "Rajkot", "Varanasi", "Amritsar", "Allahabad", "Howrah"],
  },
  {
    code: "ID",
    name: "Indonésie",
    flag: "🇮🇩",
    dialCode: "+62",
    cities: ["Jakarta", "Surabaya", "Bandung", "Bekasi", "Medan", "Tangerang", "Depok", "Semarang", "Palembang", "Makassar", "Tangerang Selatan", "Batam", "Bogor", "Pekanbaru", "Bandar Lampung", "Malang", "Padang", "Denpasar", "Samarinda", "Tasikmalaya", "Pontianak", "Cimahi", "Balikpapan", "Jambi", "Surakarta"],
  },
  {
    code: "IQ",
    name: "Irak",
    flag: "🇮🇶",
    dialCode: "+964",
    cities: ["Bagdad", "Bassorah", "Mossoul", "Erbil", "Souleimaniye", "Nadjaf", "Kerbala", "Kirkouk", "Nasiriya", "Amarah", "Divaniya", "Koût", "Hillah", "Dohuk", "Ramadi", "Falloujah", "Samarra", "Baqubah", "Tikrit"],
  },
  {
    code: "IR",
    name: "Iran",
    flag: "🇮🇷",
    dialCode: "+98",
    cities: ["Téhéran", "Mashhad", "Ispahan", "Karaj", "Chiraz", "Tabriz", "Qom", "Ahvaz", "Kermanchah", "Ourmia", "Zahedan", "Rasht", "Kerman", "Hamadan", "Arak", "Yazd", "Ardabil", "Bandar Abbas", "Zandjan", "Sanandaj", "Qazvin", "Khorramabad", "Gorgan", "Sari", "Kachan"],
  },
  {
    code: "IL",
    name: "Israël",
    flag: "🇮🇱",
    dialCode: "+972",
    cities: ["Jérusalem", "Tel-Aviv", "Haïfa", "Rishon LeZion", "Petah Tikva", "Ashdod", "Netanya", "Beer-Sheva", "Holon", "Bnei Brak", "Ramat Gan", "Ashkelon", "Rehovot", "Bat Yam", "Beit Shemesh", "Kfar Saba", "Herzliya", "Hadera", "Modiin", "Nazareth"],
  },
  {
    code: "JP",
    name: "Japon",
    flag: "🇯🇵",
    dialCode: "+81",
    cities: ["Tokyo", "Yokohama", "Osaka", "Nagoya", "Sapporo", "Fukuoka", "Kobe", "Kyoto", "Kawasaki", "Saitama", "Hiroshima", "Sendai", "Kitakyushu", "Chiba", "Sakai", "Niigata", "Hamamatsu", "Shizuoka", "Sagamihara", "Okayama", "Kumamoto", "Kagoshima", "Funabashi", "Hachioji", "Kawaguchi"],
  },
  {
    code: "JO",
    name: "Jordanie",
    flag: "🇯🇴",
    dialCode: "+962",
    cities: ["Amman", "Zarqa", "Irbid", "Russeifa", "Quwaysimah", "Wadi as-Ser", "Tila al-Ali", "Khraybat as-Souq", "Aqaba", "As-Salt", "Madaba", "Ar-Ramtha", "Al-Mafraq", "Ma'an", "Jerash", "Ajloun", "Karak", "Tafileh"],
  },
  {
    code: "KZ",
    name: "Kazakhstan",
    flag: "🇰🇿",
    dialCode: "+7",
    cities: ["Almaty", "Astana", "Chimkent", "Karaganda", "Aktobe", "Taraz", "Pavlodar", "Oust-Kamenogorsk", "Semey", "Atyrau", "Kyzylorda", "Kostanaï", "Ouralsk", "Petropavl", "Temirtaou", "Aktaou", "Turkestan", "Koktchétav", "Taldykurgan", "Ekibastouz"],
  },
  {
    code: "KG",
    name: "Kirghizistan",
    flag: "🇰🇬",
    dialCode: "+996",
    cities: ["Bichkek", "Och", "Djalal-Abad", "Karakol", "Tokmok", "Özgön", "Bazar-Korgon", "Naryn", "Talas", "Isfana", "Kara-Balta", "Mailuu-Suu", "Kant", "Kara-Suu", "Balykchy"],
  },
  {
    code: "KW",
    name: "Koweït",
    flag: "🇰🇼",
    dialCode: "+965",
    cities: ["Koweït", "Al Ahmadi", "Hawalli", "As Salimiyah", "Sabah as Salim", "Al Farwaniyah", "Al Fahahil", "Ar Riqqah", "Ar Rumaythiyah", "Al Jahra", "Bayan", "Salwa", "Mangaf", "Al Fintas", "Abu Fatira"],
  },
  {
    code: "LA",
    name: "Laos",
    flag: "🇱🇦",
    dialCode: "+856",
    cities: ["Vientiane", "Paksé", "Savannakhet", "Luang Prabang", "Thakhek", "Muang Xay", "Phonsavan", "Luang Namtha", "Sam Neua", "Champasak", "Paksan", "Attapeu", "Salavan", "Xam Nua", "Ban Houayxay"],
  },
  {
    code: "LB",
    name: "Liban",
    flag: "🇱🇧",
    dialCode: "+961",
    cities: ["Beyrouth", "Tripoli", "Sidon", "Tyr", "Jounieh", "Zahlé", "Byblos", "Baalbek", "Batroun", "Nabatiyé", "Aley", "Zgharta", "Bcharré", "Jezzine", "Anjar"],
  },
  {
    code: "MY",
    name: "Malaisie",
    flag: "🇲🇾",
    dialCode: "+60",
    cities: ["Kuala Lumpur", "George Town", "Ipoh", "Johor Bahru", "Petaling Jaya", "Shah Alam", "Kuching", "Kota Kinabalu", "Klang", "Subang Jaya", "Tebrau", "Kajang", "Seremban", "Ampang Jaya", "Kuantan", "Sungai Petani", "Iskandar Puteri", "Malacca", "Sandakan", "Alor Setar"],
  },
  {
    code: "MV",
    name: "Maldives",
    flag: "🇲🇻",
    dialCode: "+960",
    cities: ["Malé", "Addu City", "Fuvahmulah", "Kulhudhuffushi", "Thinadhoo", "Naifaru", "Hithadhoo", "Dhidhdhoo", "Eydhafushi", "Villingili"],
  },
  {
    code: "MN",
    name: "Mongolie",
    flag: "🇲🇳",
    dialCode: "+976",
    cities: ["Oulan-Bator", "Erdenet", "Darkhan", "Choibalsan", "Moron", "Nalaikh", "Baganuur", "Ölgii", "Khovd", "Dalanzadgad", "Öndörkhaan", "Zuunmod", "Baruun-Urt", "Sainshand", "Altai"],
  },
  {
    code: "MM",
    name: "Myanmar",
    flag: "🇲🇲",
    dialCode: "+95",
    cities: ["Rangoun", "Mandalay", "Naypyidaw", "Mawlamyine", "Bago", "Pathein", "Monywa", "Meiktila", "Sittwe", "Myeik", "Taunggyi", "Myitkyina", "Dawei", "Pyay", "Hpa-An", "Magway", "Pakokku", "Loikaw", "Lashio", "Kengtung"],
  },
  {
    code: "NP",
    name: "Népal",
    flag: "🇳🇵",
    dialCode: "+977",
    cities: ["Katmandou", "Pokhara", "Lalitpur", "Biratnagar", "Bharatpur", "Birgunj", "Butwal", "Dharan", "Bhaktapur", "Janakpur", "Dhangadhi", "Hetauda", "Itahari", "Nepalgunj", "Birendranagar", "Tulsipur", "Damak", "Rajbiraj", "Lahan", "Gaur"],
  },
  {
    code: "OM",
    name: "Oman",
    flag: "🇴🇲",
    dialCode: "+968",
    cities: ["Mascate", "Seeb", "Salalah", "Bawshar", "Sohar", "As Suwayq", "Ibri", "Saham", "Barka", "Rustaq", "Al Buraimi", "Nizwa", "Sur", "Bahla", "Al Khaboura"],
  },
  {
    code: "UZ",
    name: "Ouzbékistan",
    flag: "🇺🇿",
    dialCode: "+998",
    cities: ["Tachkent", "Samarcande", "Namangan", "Andijan", "Noukous", "Boukhara", "Karchi", "Fergana", "Kokand", "Margilan", "Djizak", "Ourguentch", "Chirchik", "Termez", "Angren", "Navoi", "Almalyk", "Denau", "Goulistan", "Zarafshan"],
  },
  {
    code: "PK",
    name: "Pakistan",
    flag: "🇵🇰",
    dialCode: "+92",
    cities: ["Karachi", "Lahore", "Faisalabad", "Rawalpindi", "Gujranwala", "Peshawar", "Multan", "Hyderabad", "Islamabad", "Quetta", "Bahawalpur", "Sargodha", "Sialkot", "Sukkur", "Larkana", "Sheikhupura", "Jhang", "Rahim Yar Khan", "Gujrat", "Mardan", "Kasur", "Mingora", "Dera Ghazi Khan", "Sahiwal", "Nawabshah"],
  },
  {
    code: "PS",
    name: "Palestine",
    flag: "🇵🇸",
    dialCode: "+970",
    cities: ["Gaza", "Hébron", "Naplouse", "Khan Younès", "Jabalia", "Rafah", "Deir al-Balah", "Ramallah", "Bethléem", "Jénine", "Tulkarem", "Qalqilya", "Beit Lahia", "Jéricho", "Beit Hanoun"],
  },
  {
    code: "PH",
    name: "Philippines",
    flag: "🇵🇭",
    dialCode: "+63",
    cities: ["Manille", "Quezon City", "Davao", "Caloocan", "Cebu", "Zamboanga", "Taguig", "Antipolo", "Pasig", "Cagayan de Oro", "Parañaque", "Dasmariñas", "Valenzuela", "Bacoor", "General Santos", "Las Piñas", "Makati", "Bacolod", "Muntinlupa", "San Jose del Monte", "Marikina", "Angeles", "Imus", "Iloilo", "Pasay"],
  },
  {
    code: "QA",
    name: "Qatar",
    flag: "🇶🇦",
    dialCode: "+974",
    cities: ["Doha", "Al Rayyan", "Al Wakrah", "Al Khor", "Umm Salal", "Al Daayen", "Madinat ash Shamal", "Mesaieed", "Dukhan", "Al Wukair"],
  },
  {
    code: "SG",
    name: "Singapour",
    flag: "🇸🇬",
    dialCode: "+65",
    cities: ["Singapour", "Woodlands", "Jurong West", "Tampines", "Hougang", "Sengkang", "Punggol", "Yishun", "Bukit Batok", "Choa Chu Kang"],
  },
  {
    code: "LK",
    name: "Sri Lanka",
    flag: "🇱🇰",
    dialCode: "+94",
    cities: ["Colombo", "Dehiwala-Mount Lavinia", "Moratuwa", "Sri Jayawardenepura Kotte", "Negombo", "Kandy", "Kalmunai", "Vavuniya", "Galle", "Trincomalee", "Batticaloa", "Jaffna", "Anuradhapura", "Ratnapura", "Badulla", "Matara", "Kurunegala", "Puttalam", "Nuwara Eliya", "Hambantota"],
  },
  {
    code: "SY",
    name: "Syrie",
    flag: "🇸🇾",
    dialCode: "+963",
    cities: ["Damas", "Alep", "Homs", "Lattaquié", "Hama", "Raqqa", "Deir ez-Zor", "Hassaké", "Qamichli", "Tartous", "Idleb", "Daraa", "Douma", "As-Suwayda", "Manbij"],
  },
  {
    code: "TJ",
    name: "Tadjikistan",
    flag: "🇹🇯",
    dialCode: "+992",
    cities: ["Douchanbé", "Khodjent", "Kouliab", "Qurghonteppa", "Istaravshan", "Vahdat", "Konibodom", "Tursunzoda", "Isfara", "Panjakent", "Khorugh", "Ghafurov", "Somoniyon", "Norak", "Buston"],
  },
  {
    code: "TW",
    name: "Taïwan",
    flag: "🇹🇼",
    dialCode: "+886",
    cities: ["Taipei", "Kaohsiung", "Taichung", "Tainan", "Banqiao", "Taoyuan", "Hsinchu", "Keelung", "Zhongli", "Chiayi", "Tainan", "Fengshan", "Sanchong", "Zhonghe", "Xinzhuang", "New Taipei", "Changhua", "Pingtung", "Yilan", "Hualien"],
  },
  {
    code: "TH",
    name: "Thaïlande",
    flag: "🇹🇭",
    dialCode: "+66",
    cities: ["Bangkok", "Samut Prakan", "Nonthaburi", "Udon Thani", "Chiang Mai", "Hat Yai", "Pak Kret", "Khon Kaen", "Chaophraya Surasak", "Nakhon Ratchasima", "Pattaya", "Chiang Rai", "Ubon Ratchathani", "Nakhon Sawan", "Surat Thani", "Phuket", "Nakhon Pathom", "Phitsanulok", "Songkhla", "Lampang"],
  },
  {
    code: "TL",
    name: "Timor oriental",
    flag: "🇹🇱",
    dialCode: "+670",
    cities: ["Dili", "Baucau", "Lospalos", "Maliana", "Suai", "Liquiça", "Aileu", "Ermera", "Gleno", "Same"],
  },
  {
    code: "TM",
    name: "Turkménistan",
    flag: "🇹🇲",
    dialCode: "+993",
    cities: ["Achgabat", "Türkmenabat", "Daşoguz", "Mary", "Balkanabat", "Bayramaly", "Türkmenbaşy", "Tejen", "Abadan", "Atamyrat", "Yolöten", "Kaka", "Serdar", "Gumdag", "Gazojak"],
  },
  {
    code: "TR",
    name: "Turquie",
    flag: "🇹🇷",
    dialCode: "+90",
    cities: ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Adana", "Konya", "Gaziantep", "Mersin", "Diyarbakir", "Kayseri", "Eskişehir", "Samsun", "Denizli", "Şanlıurfa", "Adapazarı", "Malatya", "Kahramanmaraş", "Erzurum", "Van", "Batman", "Elâzığ", "Trabzon", "Manisa", "Gebze"],
  },
  {
    code: "VN",
    name: "Viêt Nam",
    flag: "🇻🇳",
    dialCode: "+84",
    cities: ["Hô Chi Minh-Ville", "Hanoï", "Haiphong", "Đà Nẵng", "Cần Thơ", "Biên Hòa", "Nha Trang", "Huế", "Buôn Ma Thuột", "Quy Nhơn", "Vũng Tàu", "Nam Định", "Hạ Long", "Vinh", "Đà Lạt", "Thanh Hóa", "Thái Nguyên", "Mỹ Tho", "Long Xuyên", "Phan Thiết"],
  },
  {
    code: "YE",
    name: "Yémen",
    flag: "🇾🇪",
    dialCode: "+967",
    cities: ["Sanaa", "Aden", "Taïz", "Al Hudaydah", "Ibb", "Mukalla", "Dhamar", "Amran", "Sayyan", "Zinjibar", "Zabid", "Hajjah", "Sa'dah", "Lahij", "Al Bayda"],
  },

  // Océanie
  {
    code: "AU",
    name: "Australie",
    flag: "🇦🇺",
    dialCode: "+61",
    cities: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast", "Canberra", "Newcastle", "Wollongong", "Logan City", "Geelong", "Hobart", "Townsville", "Cairns", "Darwin", "Toowoomba", "Ballarat", "Bendigo", "Launceston", "Mackay", "Rockhampton", "Bundaberg", "Bunbury", "Hervey Bay", "Wagga Wagga"],
  },
  {
    code: "FJ",
    name: "Fidji",
    flag: "🇫🇯",
    dialCode: "+679",
    cities: ["Suva", "Lautoka", "Nadi", "Labasa", "Ba", "Levuka", "Savusavu", "Nausori", "Sigatoka", "Rakiraki"],
  },
  {
    code: "KI",
    name: "Kiribati",
    flag: "🇰🇮",
    dialCode: "+686",
    cities: ["South Tarawa", "Betio", "Bikenibeu", "Bairiki", "Teaoraereke", "Eita", "Bonriki", "Tabwakea", "Ambo", "London"],
  },
  {
    code: "MH",
    name: "Îles Marshall",
    flag: "🇲🇭",
    dialCode: "+692",
    cities: ["Majuro", "Ebeye", "Arno", "Jabor", "Wotje", "Mili", "Namdrik", "Ailinglaplap", "Kili", "Jaluit"],
  },
  {
    code: "FM",
    name: "Micronésie",
    flag: "🇫🇲",
    dialCode: "+691",
    cities: ["Palikir", "Weno", "Kolonia", "Tofol", "Lelu", "Colonia"],
  },
  {
    code: "NR",
    name: "Nauru",
    flag: "🇳🇷",
    dialCode: "+674",
    cities: ["Yaren", "Denigomodu", "Meneng", "Aiwo", "Boe", "Buada", "Anetan", "Uaboe", "Baiti", "Anabar"],
  },
  {
    code: "NZ",
    name: "Nouvelle-Zélande",
    flag: "🇳🇿",
    dialCode: "+64",
    cities: ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga", "Napier-Hastings", "Dunedin", "Palmerston North", "Nelson", "Rotorua", "New Plymouth", "Whangarei", "Invercargill", "Whanganui", "Gisborne", "Queenstown", "Timaru", "Blenheim", "Taupo", "Masterton"],
  },
  {
    code: "PW",
    name: "Palaos",
    flag: "🇵🇼",
    dialCode: "+680",
    cities: ["Ngerulmud", "Koror", "Airai", "Meyungs", "Kloulklubed"],
  },
  {
    code: "PG",
    name: "Papouasie-Nouvelle-Guinée",
    flag: "🇵🇬",
    dialCode: "+675",
    cities: ["Port Moresby", "Lae", "Mount Hagen", "Madang", "Wewak", "Goroka", "Kokopo", "Kimbe", "Popondetta", "Arawa", "Mendi", "Alotau", "Daru", "Vanimo", "Kavieng"],
  },
  {
    code: "WS",
    name: "Samoa",
    flag: "🇼🇸",
    dialCode: "+685",
    cities: ["Apia", "Asau", "Mulifanua", "Afega", "Leulumoega", "Lufilufi", "Salelavalu", "Siumu", "Faleasiu", "Vaitele"],
  },
  {
    code: "SB",
    name: "Îles Salomon",
    flag: "🇸🇧",
    dialCode: "+677",
    cities: ["Honiara", "Gizo", "Auki", "Noro", "Tulagi", "Kirakira", "Buala", "Lata", "Taro", "Munda"],
  },
  {
    code: "TO",
    name: "Tonga",
    flag: "🇹🇴",
    dialCode: "+676",
    cities: ["Nukuʻalofa", "Neiafu", "Haveluloto", "Vaini", "Pangai", "Ohonua", "Hihifo", "ʻEua", "Kolonga", "Lapaha"],
  },
  {
    code: "TV",
    name: "Tuvalu",
    flag: "🇹🇻",
    dialCode: "+688",
    cities: ["Funafuti", "Asau", "Tanrake", "Savave", "Kulia", "Lolua", "Fakaifou", "Alapi"],
  },
  {
    code: "VU",
    name: "Vanuatu",
    flag: "🇻🇺",
    dialCode: "+678",
    cities: ["Port-Vila", "Luganville", "Norsup", "Port-Olry", "Isangel", "Sola", "Lakatoro", "Lenakel", "Saratamata", "Longana"],
  },
];

// Tri par nom
export const COUNTRIES = COUNTRIES_DATA.sort((a, b) => a.name.localeCompare(b.name, "fr"));

// Fonction pour trouver un pays par son code
export function getCountryByCode(code: string): CountryData | undefined {
  return COUNTRIES.find(c => c.code === code);
}

// Fonction pour trouver un pays par son indicatif
export function getCountryByDialCode(dialCode: string): CountryData | undefined {
  return COUNTRIES.find(c => c.dialCode === dialCode);
}

// Fonction pour trouver le pays d'une ville
export function findCountryByCity(cityName: string): CountryData | undefined {
  if (!cityName) return undefined;
  const normalizedCity = cityName.toLowerCase().trim();
  return COUNTRIES.find(country =>
    country.cities.some(c => c.toLowerCase() === normalizedCity)
  );
}

// Extraire l'indicatif et le numéro d'un numéro de téléphone
export function parsePhoneNumber(phone: string): { dialCode: string; number: string } {
  if (!phone) return { dialCode: "+212", number: "" };

  // Trier les indicatifs par longueur décroissante pour matcher les plus longs d'abord
  const sortedCountries = [...COUNTRIES].sort((a, b) => b.dialCode.length - a.dialCode.length);

  for (const country of sortedCountries) {
    if (phone.startsWith(country.dialCode)) {
      let num = phone.slice(country.dialCode.length).trim();
      // Strip leading 0 (e.g. +2120623... → 623...)
      if (num.startsWith("0") && num.length > 1) num = num.slice(1);
      return {
        dialCode: country.dialCode,
        number: num,
      };
    }
  }

  // Par défaut, Maroc
  let fallbackNum = phone.replace(/^\+/, "");
  if (fallbackNum.startsWith("0") && fallbackNum.length > 1) fallbackNum = fallbackNum.slice(1);
  return { dialCode: "+212", number: fallbackNum };
}
